package com.cs.util;


import org.apache.commons.lang3.StringUtils;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Created by chensheng350 on 2017/7/12.
 */
public class EmojiUtil {
	/**
	 * 匹配emoji区间正则
	 */
	private final static Pattern p_emoji = Pattern.compile("[\ud800\udc00-\udbff\udfff\ud800-\udfff]");
	/**
	 * 匹配qq表情正则
	 * 放在后面初始化
	 */
	private final static Pattern p_qq ;

	/**
	 *
	 * 将文本中的qq表情转换成emoji表情
	 * @param qqContent
	 * @return
	 */
	public static String convertQQ2Emoji(String qqContent){
		if(StringUtils.isBlank(qqContent)){
			return "";
		}

		StringBuffer sb = new StringBuffer();
		Matcher m_qq = p_qq.matcher(qqContent);
		while(m_qq.find()){
			String qq = m_qq.group();
			try {
				String replacement = convertSingleQQ2Emoji(qq);
				m_qq.appendReplacement(sb, replacement);
			}catch (Exception e){
			}
		}
		m_qq.appendTail(sb);
		return sb.toString();
	}

	/**
	 * 将文本中的emoji表情转换成qq表情
	 * @param emojiContent
	 * @return
	 */
	public static String convertEmoji2QQ(String emojiContent){
		if(StringUtils.isBlank(emojiContent)){
			return "";
		}

		StringBuffer sb = new StringBuffer();

		Matcher m_emoji = p_emoji.matcher(emojiContent);
		while(m_emoji.find()){
			String emoji = m_emoji.group();
			try {
				String replacement = convertSingleEmoji2QQ(emoji);
				m_emoji.appendReplacement(sb, replacement);
			}catch (Exception e){
				e.printStackTrace();
			}
		}
		m_emoji.appendTail(sb);
		return sb.toString();
	}

	/**
	 * 将单个emoji 转换成qq表情
	 *
	 * 当emoji和qq存在映射关系
	 * 	返回映射的qq表情
	 * 当emoji全集里面包含
	 * 	返回emoji描述
	 *
	 * 否则返回emoji代码
	 * @param emoji
	 * @return
	 */
	private static String convertSingleEmoji2QQ(String emoji) throws Exception {
		int cpCount = emoji.codePointCount(0, emoji.length());
		int firCodeIndex = emoji.offsetByCodePoints(0, 0);
		int lstCodeIndex = emoji.offsetByCodePoints(0, cpCount - 1);
		StringBuilder sb = new StringBuilder(emoji.length());
		for (int index = firCodeIndex; index <= lstCodeIndex;index++) {
			int codePoint = emoji.codePointAt(index);
			String hash = Integer.toHexString(codePoint);
			sb.append(hash);
		}
		String hexCode = String.format("U+%s", sb.toString().toUpperCase());

		if(emojiQQMap.containsKey(hexCode)){
			return emojiQQMap.get(hexCode).getQqCode();
		}

		if(allEmojiMap.containsKey(hexCode)){
			return String.format("[em]%s[/em]", allEmojiMap.get(hexCode));
		}

		return String.format("[em]%s[/em]", hexCode);
	}

	/**
	 * 将单个qq 转换成emoji表情
	 *
	 * 当存在qq和emoji的映射关系
	 * 	返回emoji编码
	 * 	当qq词条
	 * 	返回qq中文描述
	 * 否则不作处理
	 * @param qqCode
	 * @return
	 */
	private static String convertSingleQQ2Emoji(String qqCode) throws Exception {
		if(qqEmojiMap.containsKey(qqCode)){
			String emojiCode = qqEmojiMap.get(qqCode).getEmojiCode();
			String[] split = emojiCode.split(" ");

			List<String> charList = new ArrayList<String>();
			for (String s : split) {
				int i = Integer.parseInt(s.substring(2), 16);
				charList.add(new String(Character.toChars(i)));
			}
			return StringUtils.join(charList, "");
		}

		if(allQQMap.containsKey(qqCode)){
			return String.format("[%s]", allQQMap.get(qqCode));
		}

		return qqCode;
	}

	public static void main(String[] args){
		System.out.println(convertEmoji2QQ("我二十\uD83C\uDF3A~~~~"));


		for (String s : qqEmojiMap.keySet()) {
			System.out.println(String.format("%s->%s", s, convertQQ2Emoji(s)));
		}
		System.out.println(convertQQ2Emoji("/:&-("));
	}

	/**
	 * qqEmoji映射关系  由内部人员整理
	 *
	 * 映射关系需要修改
	 */
	private final static List<EmojiQQBean> qqEmojiBeanList = new ArrayList<EmojiQQBean>();
	static {
		qqEmojiBeanList.add(new EmojiQQBean("[撇嘴]", "U+1F61F", "撇嘴"));
		qqEmojiBeanList.add(new EmojiQQBean("[色]", "U+1F60D", "色"));
		qqEmojiBeanList.add(new EmojiQQBean("[发呆]", "U+1F633", "发呆"));
		qqEmojiBeanList.add(new EmojiQQBean("[得意]", "U+1F60E", "得意"));
		qqEmojiBeanList.add(new EmojiQQBean("[流泪]", "U+1F62D", "流泪"));
		qqEmojiBeanList.add(new EmojiQQBean("[微笑]", "U+1F60A", "微笑"));
		qqEmojiBeanList.add(new EmojiQQBean("[睡]", "U+1F634", "睡"));
		qqEmojiBeanList.add(new EmojiQQBean("[大哭]", "U+1F62D", "大哭"));
		qqEmojiBeanList.add(new EmojiQQBean("[发怒]", "U+1F624", "发怒"));
		qqEmojiBeanList.add(new EmojiQQBean("[调皮]", "U+1F61D", "调皮"));
		qqEmojiBeanList.add(new EmojiQQBean("[呲牙]", "U+1F62C", "呲牙"));
		qqEmojiBeanList.add(new EmojiQQBean("[惊讶]", "U+1F62E", "惊讶"));
		qqEmojiBeanList.add(new EmojiQQBean("[难过]", "U+1F61F", "难过"));
		qqEmojiBeanList.add(new EmojiQQBean("[酷]", "U+1F60E", "酷"));
		qqEmojiBeanList.add(new EmojiQQBean("[冷汗]", "U+1F613", "冷汗"));
		qqEmojiBeanList.add(new EmojiQQBean("[愉快]", "U+263A", "愉快"));
		qqEmojiBeanList.add(new EmojiQQBean("[惊恐]", "U+1F631", "惊恐"));
		qqEmojiBeanList.add(new EmojiQQBean("[鼓掌]", "U+1F44F", "鼓掌"));
		qqEmojiBeanList.add(new EmojiQQBean("[亲亲]", "U+1F61A", "亲亲"));
		qqEmojiBeanList.add(new EmojiQQBean("[西瓜]", "U+1F349", "西瓜"));
		qqEmojiBeanList.add(new EmojiQQBean("[啤酒]", "U+1F37B", "啤酒"));
		qqEmojiBeanList.add(new EmojiQQBean("[篮球]", "U+1F3C0", "篮球"));
		qqEmojiBeanList.add(new EmojiQQBean("[咖啡]", "U+2615", "咖啡"));
		qqEmojiBeanList.add(new EmojiQQBean("[饭]", "U+1F35A", "饭"));
		qqEmojiBeanList.add(new EmojiQQBean("[猪头]", "U+1F437", "猪头"));
		qqEmojiBeanList.add(new EmojiQQBean("[玫瑰]", "U+1F339", "玫瑰"));
		qqEmojiBeanList.add(new EmojiQQBean("[嘴唇]", "U+1F48B", "嘴唇"));
		qqEmojiBeanList.add(new EmojiQQBean("[心碎]", "U+1F494", "心碎"));
		qqEmojiBeanList.add(new EmojiQQBean("[蛋糕]", "U+1F382", "蛋糕"));
		qqEmojiBeanList.add(new EmojiQQBean("[闪电]", "U+26A1", "闪电"));
		qqEmojiBeanList.add(new EmojiQQBean("[炸弹]", "U+1F4A3", "炸弹"));
		qqEmojiBeanList.add(new EmojiQQBean("[足球]", "U+26BD", "足球"));
		qqEmojiBeanList.add(new EmojiQQBean("[便便]", "U+1F4A9", "便便"));
		qqEmojiBeanList.add(new EmojiQQBean("[月亮]", "U+1F319", "月亮"));
		qqEmojiBeanList.add(new EmojiQQBean("[太阳]", "U+2600", "太阳"));
		qqEmojiBeanList.add(new EmojiQQBean("[礼物]", "U+1F381", "礼物"));
		qqEmojiBeanList.add(new EmojiQQBean("[强]", "U+1F44D", "强"));
		qqEmojiBeanList.add(new EmojiQQBean("[弱]", "U+1F44E", "弱"));
		qqEmojiBeanList.add(new EmojiQQBean("[胜利]", "U+270C", "胜利"));
		qqEmojiBeanList.add(new EmojiQQBean("[拳头]", "U+1F44A", "拳头"));
		qqEmojiBeanList.add(new EmojiQQBean("[OK]", "U+1F44C", "OK"));



	}

	private final static Map<String, EmojiQQBean> qqEmojiMap = new HashMap<String, EmojiQQBean>();
	private final static Map<String, EmojiQQBean> emojiQQMap = new HashMap<String, EmojiQQBean>();
	static{
		for (EmojiQQBean emojiQQBean : qqEmojiBeanList) {
			emojiQQMap.put(emojiQQBean.getEmojiCode(), emojiQQBean);
			qqEmojiMap.put(emojiQQBean.getQqCode(), emojiQQBean);
		}
	}

	/**
	 * 所有qq表情合集
	 * 后续可能会拓展
	 * 参考: http://www.onegreen.net/QQ/HTML/53998.html
	 */
	private final static Map<String, String> allQQMap = new HashMap<String, String>();
	static{

		allQQMap.put("[撇嘴]", "[撇嘴]");
		allQQMap.put("[色]", "[色]");
		allQQMap.put("[发呆]", "[发呆]");
		allQQMap.put("[得意]", "[得意]");
		allQQMap.put("[流泪]", "[流泪]");
		allQQMap.put("[害羞]", "[害羞]");
		allQQMap.put("[微笑]", "[微笑]");
		allQQMap.put("[闭嘴]", "[闭嘴]");
		allQQMap.put("[睡]", "[睡]");
		allQQMap.put("[大哭]", "[大哭]");
		allQQMap.put("[尴尬]", "[尴尬]");
		allQQMap.put("[发怒]", "[发怒]");
		allQQMap.put("[调皮]", "[调皮]");
		allQQMap.put("[呲牙]", "[呲牙]");
		allQQMap.put("[惊讶]", "[惊讶]");
		allQQMap.put("[难过]", "[难过]");
		allQQMap.put("[酷]", "[酷]");
		allQQMap.put("[冷汗]", "[冷汗]");
		allQQMap.put("[抓狂]", "[抓狂]");
		allQQMap.put("[吐]", "[吐]");
		allQQMap.put("[偷笑]", "[偷笑]");
		allQQMap.put("[愉快]", "[愉快]");
		allQQMap.put("[白眼]", "[白眼]");
		allQQMap.put("[傲慢]", "[傲慢]");
		allQQMap.put("[饥饿]", "[饥饿]");
		allQQMap.put("[困]", "[困]");
		allQQMap.put("[惊恐]", "[惊恐]");
		allQQMap.put("[流汗]", "[流汗]");
		allQQMap.put("[憨笑]", "[憨笑]");
		allQQMap.put("[悠闲]", "[悠闲]");
		allQQMap.put("[奋斗]", "[奋斗]");
		allQQMap.put("[咒骂]", "[咒骂]");
		allQQMap.put("[疑问]", "[疑问]");
		allQQMap.put("[嘘]", "[嘘]");
		allQQMap.put("[晕]", "[晕]");
		allQQMap.put("[疯了]", "[疯了]");
		allQQMap.put("[衰]", "[衰]");
		allQQMap.put("[骷髅]", "[骷髅]");
		allQQMap.put("[敲打]", "[敲打]");
		allQQMap.put("[再见]", "[再见]");
		allQQMap.put("[擦汗]", "[擦汗]");
		allQQMap.put("[抠鼻]", "[抠鼻]");
		allQQMap.put("[鼓掌]", "[鼓掌]");
		allQQMap.put("[糗大了]", "[糗大了]");
		allQQMap.put("[坏笑]", "[坏笑]");
		allQQMap.put("[左哼哼]", "[左哼哼]");
		allQQMap.put("[右哼哼]", "[右哼哼]");
		allQQMap.put("[哈欠]", "[哈欠]");
		allQQMap.put("[鄙视]", "[鄙视]");
		allQQMap.put("[委屈]", "[委屈]");
		allQQMap.put("[快哭了]", "[快哭了]");
		allQQMap.put("[阴险]", "[阴险]");
		allQQMap.put("[亲亲]", "[亲亲]");
		allQQMap.put("[吓]", "[吓]");
		allQQMap.put("[可怜]", "[可怜]");
		allQQMap.put("[菜刀]", "[菜刀]");
		allQQMap.put("[西瓜]", "[西瓜]");
		allQQMap.put("[啤酒]", "[啤酒]");
		allQQMap.put("[篮球]", "[篮球]");
		allQQMap.put("[乒乓]", "[乒乓]");
		allQQMap.put("[咖啡]", "[咖啡]");
		allQQMap.put("[饭]", "[饭]");
		allQQMap.put("[猪头]", "[猪头]");
		allQQMap.put("[玫瑰]", "[玫瑰]");
		allQQMap.put("[凋谢]", "[凋谢]");
		allQQMap.put("[嘴唇]", "[嘴唇]");
		allQQMap.put("[爱心]", "[爱心]");
		allQQMap.put("[心碎]", "[心碎]");
		allQQMap.put("[蛋糕]", "[蛋糕]");
		allQQMap.put("[闪电]", "[闪电]");
		allQQMap.put("[炸弹]", "[炸弹]");
		allQQMap.put("[刀]", "[刀]");
		allQQMap.put("[足球]", "[足球]");
		allQQMap.put("[瓢虫]", "[瓢虫]");
		allQQMap.put("[便便]", "[便便]");
		allQQMap.put("[月亮]", "[月亮]");
		allQQMap.put("[太阳]", "[太阳]");
		allQQMap.put("[礼物]", "[礼物]");
		allQQMap.put("[拥抱]", "[拥抱]");
		allQQMap.put("[强]", "[强]");
		allQQMap.put("[弱]", "[弱]");
		allQQMap.put("[握手]", "[握手]");
		allQQMap.put("[胜利]", "[胜利]");
		allQQMap.put("[抱拳]", "[抱拳]");
		allQQMap.put("[勾引]", "[勾引]");
		allQQMap.put("[拳头]", "[拳头]");
		allQQMap.put("[差劲]", "[差劲]");
		allQQMap.put("[爱你]", "[爱你]");
		allQQMap.put("[NO]", "[NO]");
		allQQMap.put("[OK]", "[OK]");
		allQQMap.put("[爱情]", "[爱情]");
		allQQMap.put("[飞吻]", "[飞吻]");
		allQQMap.put("[跳跳]", "[跳跳]");
		allQQMap.put("[发抖]", "[发抖]");
		allQQMap.put("[怄火]", "[怄火]");
		allQQMap.put("[转圈]", "[转圈]");
		allQQMap.put("[磕头]", "[磕头]");
		allQQMap.put("[回头]", "[回头]");
		allQQMap.put("[跳绳]", "[跳绳]");
		allQQMap.put("[投降]", "[投降]");
		allQQMap.put("[激动]", "[激动]");
		allQQMap.put("[乱舞]", "[乱舞]");
		allQQMap.put("[献吻]", "[献吻]");
		allQQMap.put("[左太极]", "[左太极]");
		allQQMap.put("[右太极]", "[右太极]");


		//用于匹配所有qq表情
		//*.-()[]{}?|+^$  处理qq表情中的特殊字符

		Set<String> qqRegexpSet = new HashSet<String>();
		for (String key : allQQMap.keySet()) {
			String processedKey = key
									.replace("[", "\\[")
									.replace("]", "\\]");
			qqRegexpSet.add(String.format("(%s)", processedKey));
		}
		p_qq = Pattern.compile(StringUtils.join(qqRegexpSet, "|"));
		//System.out.println(p_qq.toString());
	}


	/**
	 * 所有emoji合集
	 * 后续会拓展
	 * 来源: http://www.unicode.org/emoji/charts/full-emoji-list.html
	 *
	 * 当解析不出来时 使用该emoji描述
	 */
	private final static Map<String, String> allEmojiMap = new HashMap<String, String>();;
	    static{
			allEmojiMap.put("U+1F600", "grinning face");
			allEmojiMap.put("U+1F601", "beaming face with smiling eyes");
			allEmojiMap.put("U+1F602", "face with tears of joy");
			allEmojiMap.put("U+1F923", "rolling on the floor laughing");
			allEmojiMap.put("U+1F603", "grinning face with big eyes");
			allEmojiMap.put("U+1F604", "grinning face with smiling eyes");
			allEmojiMap.put("U+1F605", "grinning face with sweat");
			allEmojiMap.put("U+1F606", "grinning squinting face");
			allEmojiMap.put("U+1F609", "winking face");
			allEmojiMap.put("U+1F60A", "smiling face with smiling eyes");
			allEmojiMap.put("U+1F60B", "face savoring food");
			allEmojiMap.put("U+1F60E", "smiling face with sunglasses");
			allEmojiMap.put("U+1F60D", "smiling face with heart-eyes");
			allEmojiMap.put("U+1F618", "face blowing a kiss");
			allEmojiMap.put("U+1F617", "kissing face");
			allEmojiMap.put("U+1F619", "kissing face with smiling eyes");
			allEmojiMap.put("U+1F61A", "kissing face with closed eyes");
			allEmojiMap.put("U+263A", "smiling face");
			allEmojiMap.put("U+1F642", "slightly smiling face");
			allEmojiMap.put("U+1F917", "hugging face");
			allEmojiMap.put("U+1F914", "thinking face");
			allEmojiMap.put("U+1F610", "neutral face");
			allEmojiMap.put("U+1F611", "expressionless face");
			allEmojiMap.put("U+1F636", "face without mouth");
			allEmojiMap.put("U+1F644", "face with rolling eyes");
			allEmojiMap.put("U+1F60F", "smirking face");
			allEmojiMap.put("U+1F623", "persevering face");
			allEmojiMap.put("U+1F625", "sad but relieved face");
			allEmojiMap.put("U+1F62E", "face with open mouth");
			allEmojiMap.put("U+1F910", "zipper-mouth face");
			allEmojiMap.put("U+1F62F", "hushed face");
			allEmojiMap.put("U+1F62A", "sleepy face");
			allEmojiMap.put("U+1F62B", "tired face");
			allEmojiMap.put("U+1F634", "sleeping face");
			allEmojiMap.put("U+1F60C", "relieved face");
			allEmojiMap.put("U+1F61B", "face with tongue");
			allEmojiMap.put("U+1F61C", "winking face with tongue");
			allEmojiMap.put("U+1F61D", "squinting face with tongue");
			allEmojiMap.put("U+1F924", "drooling face");
			allEmojiMap.put("U+1F612", "unamused face");
			allEmojiMap.put("U+1F613", "downcast face with sweat");
			allEmojiMap.put("U+1F614", "pensive face");
			allEmojiMap.put("U+1F615", "confused face");
			allEmojiMap.put("U+1F643", "upside-down face");
			allEmojiMap.put("U+1F911", "money-mouth face");
			allEmojiMap.put("U+1F632", "astonished face");
			allEmojiMap.put("U+2639", "frowning face");
			allEmojiMap.put("U+1F641", "slightly frowning face");
			allEmojiMap.put("U+1F616", "confounded face");
			allEmojiMap.put("U+1F61E", "disappointed face");
			allEmojiMap.put("U+1F61F", "worried face");
			allEmojiMap.put("U+1F624", "face with steam from nose");
			allEmojiMap.put("U+1F622", "crying face");
			allEmojiMap.put("U+1F62D", "loudly crying face");
			allEmojiMap.put("U+1F626", "frowning face with open mouth");
			allEmojiMap.put("U+1F627", "anguished face");
			allEmojiMap.put("U+1F628", "fearful face");
			allEmojiMap.put("U+1F629", "weary face");
			allEmojiMap.put("U+1F62C", "grimacing face");
			allEmojiMap.put("U+1F630", "anxious face with sweat");
			allEmojiMap.put("U+1F631", "face screaming in fear");
			allEmojiMap.put("U+1F633", "flushed face");
			allEmojiMap.put("U+1F635", "dizzy face");
			allEmojiMap.put("U+1F621", "pouting face");
			allEmojiMap.put("U+1F620", "angry face");
			allEmojiMap.put("U+1F637", "face with medical mask");
			allEmojiMap.put("U+1F912", "face with thermometer");
			allEmojiMap.put("U+1F915", "face with head-bandage");
			allEmojiMap.put("U+1F922", "nauseated face");
			allEmojiMap.put("U+1F927", "sneezing face");
			allEmojiMap.put("U+1F607", "smiling face with halo");
			allEmojiMap.put("U+1F920", "cowboy hat face");
			allEmojiMap.put("U+1F921", "clown face");
			allEmojiMap.put("U+1F925", "lying face");
			allEmojiMap.put("U+1F913", "nerd face");
			allEmojiMap.put("U+1F608", "smiling face with horns");
			allEmojiMap.put("U+1F47F", "angry face with horns");
			allEmojiMap.put("U+1F479", "ogre");
			allEmojiMap.put("U+1F47A", "goblin");
			allEmojiMap.put("U+1F480", "skull");
			allEmojiMap.put("U+2620", "skull and crossbones");
			allEmojiMap.put("U+1F47B", "ghost");
			allEmojiMap.put("U+1F47D", "alien");
			allEmojiMap.put("U+1F47E", "alien monster");
			allEmojiMap.put("U+1F916", "robot face");
			allEmojiMap.put("U+1F4A9", "pile of poo");
			allEmojiMap.put("U+1F63A", "grinning cat face");
			allEmojiMap.put("U+1F638", "grinning cat face with smiling eyes");
			allEmojiMap.put("U+1F639", "cat face with tears of joy");
			allEmojiMap.put("U+1F63B", "smiling cat face with heart-eyes");
			allEmojiMap.put("U+1F63C", "cat face with wry smile");
			allEmojiMap.put("U+1F63D", "kissing cat face");
			allEmojiMap.put("U+1F640", "weary cat face");
			allEmojiMap.put("U+1F63F", "crying cat face");
			allEmojiMap.put("U+1F63E", "pouting cat face");
			allEmojiMap.put("U+1F648", "see-no-evil monkey");
			allEmojiMap.put("U+1F649", "hear-no-evil monkey");
			allEmojiMap.put("U+1F64A", "speak-no-evil monkey");
			allEmojiMap.put("U+1F476", "baby");
			allEmojiMap.put("U+1F466", "boy");
			allEmojiMap.put("U+1F467", "girl");
			allEmojiMap.put("U+1F468", "man");
			allEmojiMap.put("U+1F469", "woman");
			allEmojiMap.put("U+1F474", "old man");
			allEmojiMap.put("U+1F475", "old woman");
			allEmojiMap.put("U+1F468 U+200D U+2695 U+FE0F", "man health worker");
			allEmojiMap.put("U+1F469 U+200D U+2695 U+FE0F", "woman health worker");
			allEmojiMap.put("U+1F468 U+200D U+1F393", "man student");
			allEmojiMap.put("U+1F469 U+200D U+1F393", "woman student");
			allEmojiMap.put("U+1F468 U+200D U+1F3EB", "man teacher");
			allEmojiMap.put("U+1F469 U+200D U+1F3EB", "woman teacher");
			allEmojiMap.put("U+1F468 U+200D U+2696 U+FE0F", "man judge");
			allEmojiMap.put("U+1F469 U+200D U+2696 U+FE0F", "woman judge");
			allEmojiMap.put("U+1F468 U+200D U+1F33E", "man farmer");
			allEmojiMap.put("U+1F469 U+200D U+1F33E", "woman farmer");
			allEmojiMap.put("U+1F468 U+200D U+1F373", "man cook");
			allEmojiMap.put("U+1F469 U+200D U+1F373", "woman cook");
			allEmojiMap.put("U+1F468 U+200D U+1F527", "man mechanic");
			allEmojiMap.put("U+1F469 U+200D U+1F527", "woman mechanic");
			allEmojiMap.put("U+1F468 U+200D U+1F3ED", "man factory worker");
			allEmojiMap.put("U+1F469 U+200D U+1F3ED", "woman factory worker");
			allEmojiMap.put("U+1F468 U+200D U+1F4BC", "man office worker");
			allEmojiMap.put("U+1F469 U+200D U+1F4BC", "woman office worker");
			allEmojiMap.put("U+1F468 U+200D U+1F52C", "man scientist");
			allEmojiMap.put("U+1F469 U+200D U+1F52C", "woman scientist");
			allEmojiMap.put("U+1F468 U+200D U+1F4BB", "man technologist");
			allEmojiMap.put("U+1F469 U+200D U+1F4BB", "woman technologist");
			allEmojiMap.put("U+1F468 U+200D U+1F3A4", "man singer");
			allEmojiMap.put("U+1F469 U+200D U+1F3A4", "woman singer");
			allEmojiMap.put("U+1F468 U+200D U+1F3A8", "man artist");
			allEmojiMap.put("U+1F469 U+200D U+1F3A8", "woman artist");
			allEmojiMap.put("U+1F468 U+200D U+2708 U+FE0F", "man pilot");
			allEmojiMap.put("U+1F469 U+200D U+2708 U+FE0F", "woman pilot");
			allEmojiMap.put("U+1F468 U+200D U+1F680", "man astronaut");
			allEmojiMap.put("U+1F469 U+200D U+1F680", "woman astronaut");
			allEmojiMap.put("U+1F468 U+200D U+1F692", "man firefighter");
			allEmojiMap.put("U+1F469 U+200D U+1F692", "woman firefighter");
			allEmojiMap.put("U+1F46E", "police officer");
			allEmojiMap.put("U+1F46E U+200D U+2642 U+FE0F", "man police officer");
			allEmojiMap.put("U+1F46E U+200D U+2640 U+FE0F", "woman police officer");
			allEmojiMap.put("U+1F575", "detective");
			allEmojiMap.put("U+1F575 U+FE0F U+200D U+2642 U+FE0F", "man detective");
			allEmojiMap.put("U+1F575 U+FE0F U+200D U+2640 U+FE0F", "woman detective");
			allEmojiMap.put("U+1F482", "guard");
			allEmojiMap.put("U+1F482 U+200D U+2642 U+FE0F", "man guard");
			allEmojiMap.put("U+1F482 U+200D U+2640 U+FE0F", "woman guard");
			allEmojiMap.put("U+1F477", "construction worker");
			allEmojiMap.put("U+1F477 U+200D U+2642 U+FE0F", "man construction worker");
			allEmojiMap.put("U+1F477 U+200D U+2640 U+FE0F", "woman construction worker");
			allEmojiMap.put("U+1F934", "prince");
			allEmojiMap.put("U+1F478", "princess");
			allEmojiMap.put("U+1F473", "person wearing turban");
			allEmojiMap.put("U+1F473 U+200D U+2642 U+FE0F", "man wearing turban");
			allEmojiMap.put("U+1F473 U+200D U+2640 U+FE0F", "woman wearing turban");
			allEmojiMap.put("U+1F472", "man with Chinese cap");
			allEmojiMap.put("U+1F471", "blond-haired person");
			allEmojiMap.put("U+1F471 U+200D U+2642 U+FE0F", "blond-haired man");
			allEmojiMap.put("U+1F471 U+200D U+2640 U+FE0F", "blond-haired woman");
			allEmojiMap.put("U+1F935", "man in tuxedo");
			allEmojiMap.put("U+1F470", "bride with veil");
			allEmojiMap.put("U+1F930", "pregnant woman");
			allEmojiMap.put("U+1F47C", "baby angel");
			allEmojiMap.put("U+1F385", "Santa Claus");
			allEmojiMap.put("U+1F64D", "person frowning");
			allEmojiMap.put("U+1F64D U+200D U+2642 U+FE0F", "man frowning");
			allEmojiMap.put("U+1F64D U+200D U+2640 U+FE0F", "woman frowning");
			allEmojiMap.put("U+1F64E", "person pouting");
			allEmojiMap.put("U+1F64E U+200D U+2642 U+FE0F", "man pouting");
			allEmojiMap.put("U+1F64E U+200D U+2640 U+FE0F", "woman pouting");
			allEmojiMap.put("U+1F645", "person gesturing NO");
			allEmojiMap.put("U+1F645 U+200D U+2642 U+FE0F", "man gesturing NO");
			allEmojiMap.put("U+1F645 U+200D U+2640 U+FE0F", "woman gesturing NO");
			allEmojiMap.put("U+1F646", "person gesturing OK");
			allEmojiMap.put("U+1F646 U+200D U+2642 U+FE0F", "man gesturing OK");
			allEmojiMap.put("U+1F646 U+200D U+2640 U+FE0F", "woman gesturing OK");
			allEmojiMap.put("U+1F481", "person tipping hand");
			allEmojiMap.put("U+1F481 U+200D U+2642 U+FE0F", "man tipping hand");
			allEmojiMap.put("U+1F481 U+200D U+2640 U+FE0F", "woman tipping hand");
			allEmojiMap.put("U+1F64B", "person raising hand");
			allEmojiMap.put("U+1F64B U+200D U+2642 U+FE0F", "man raising hand");
			allEmojiMap.put("U+1F64B U+200D U+2640 U+FE0F", "woman raising hand");
			allEmojiMap.put("U+1F647", "person bowing");
			allEmojiMap.put("U+1F647 U+200D U+2642 U+FE0F", "man bowing");
			allEmojiMap.put("U+1F647 U+200D U+2640 U+FE0F", "woman bowing");
			allEmojiMap.put("U+1F926", "person facepalming");
			allEmojiMap.put("U+1F926 U+200D U+2642 U+FE0F", "man facepalming");
			allEmojiMap.put("U+1F926 U+200D U+2640 U+FE0F", "woman facepalming");
			allEmojiMap.put("U+1F937", "person shrugging");
			allEmojiMap.put("U+1F937 U+200D U+2642 U+FE0F", "man shrugging");
			allEmojiMap.put("U+1F937 U+200D U+2640 U+FE0F", "woman shrugging");
			allEmojiMap.put("U+1F486", "person getting massage");
			allEmojiMap.put("U+1F486 U+200D U+2642 U+FE0F", "man getting massage");
			allEmojiMap.put("U+1F486 U+200D U+2640 U+FE0F", "woman getting massage");
			allEmojiMap.put("U+1F487", "person getting haircut");
			allEmojiMap.put("U+1F487 U+200D U+2642 U+FE0F", "man getting haircut");
			allEmojiMap.put("U+1F487 U+200D U+2640 U+FE0F", "woman getting haircut");
			allEmojiMap.put("U+1F6B6", "person walking");
			allEmojiMap.put("U+1F6B6 U+200D U+2642 U+FE0F", "man walking");
			allEmojiMap.put("U+1F6B6 U+200D U+2640 U+FE0F", "woman walking");
			allEmojiMap.put("U+1F3C3", "person running");
			allEmojiMap.put("U+1F3C3 U+200D U+2642 U+FE0F", "man running");
			allEmojiMap.put("U+1F3C3 U+200D U+2640 U+FE0F", "woman running");
			allEmojiMap.put("U+1F483", "woman dancing");
			allEmojiMap.put("U+1F57A", "man dancing");
			allEmojiMap.put("U+1F46F", "people with bunny ears");
			allEmojiMap.put("U+1F46F U+200D U+2642 U+FE0F", "men with bunny ears");
			allEmojiMap.put("U+1F46F U+200D U+2640 U+FE0F", "women with bunny ears");
			allEmojiMap.put("U+1F6C0", "person taking bath");
			allEmojiMap.put("U+1F6CC", "person in bed");
			allEmojiMap.put("U+1F574", "man in suit levitating");
			allEmojiMap.put("U+1F5E3", "speaking head");
			allEmojiMap.put("U+1F464", "bust in silhouette");
			allEmojiMap.put("U+1F465", "busts in silhouette");
			allEmojiMap.put("U+1F93A", "person fencing");
			allEmojiMap.put("U+1F3C7", "horse racing");
			allEmojiMap.put("U+26F7", "skier");
			allEmojiMap.put("U+1F3C2", "snowboarder");
			allEmojiMap.put("U+1F3CC", "person golfing");
			allEmojiMap.put("U+1F3CC U+FE0F U+200D U+2642 U+FE0F", "man golfing");
			allEmojiMap.put("U+1F3CC U+FE0F U+200D U+2640 U+FE0F", "woman golfing");
			allEmojiMap.put("U+1F3C4", "person surfing");
			allEmojiMap.put("U+1F3C4 U+200D U+2642 U+FE0F", "man surfing");
			allEmojiMap.put("U+1F3C4 U+200D U+2640 U+FE0F", "woman surfing");
			allEmojiMap.put("U+1F6A3", "person rowing boat");
			allEmojiMap.put("U+1F6A3 U+200D U+2642 U+FE0F", "man rowing boat");
			allEmojiMap.put("U+1F6A3 U+200D U+2640 U+FE0F", "woman rowing boat");
			allEmojiMap.put("U+1F3CA", "person swimming");
			allEmojiMap.put("U+1F3CA U+200D U+2642 U+FE0F", "man swimming");
			allEmojiMap.put("U+1F3CA U+200D U+2640 U+FE0F", "woman swimming");
			allEmojiMap.put("U+26F9", "person bouncing ball");
			allEmojiMap.put("U+26F9 U+FE0F U+200D U+2642 U+FE0F", "man bouncing ball");
			allEmojiMap.put("U+26F9 U+FE0F U+200D U+2640 U+FE0F", "woman bouncing ball");
			allEmojiMap.put("U+1F3CB", "person lifting weights");
			allEmojiMap.put("U+1F3CB U+FE0F U+200D U+2642 U+FE0F", "man lifting weights");
			allEmojiMap.put("U+1F3CB U+FE0F U+200D U+2640 U+FE0F", "woman lifting weights");
			allEmojiMap.put("U+1F6B4", "person biking");
			allEmojiMap.put("U+1F6B4 U+200D U+2642 U+FE0F", "man biking");
			allEmojiMap.put("U+1F6B4 U+200D U+2640 U+FE0F", "woman biking");
			allEmojiMap.put("U+1F6B5", "person mountain biking");
			allEmojiMap.put("U+1F6B5 U+200D U+2642 U+FE0F", "man mountain biking");
			allEmojiMap.put("U+1F6B5 U+200D U+2640 U+FE0F", "woman mountain biking");
			allEmojiMap.put("U+1F3CE", "racing car");
			allEmojiMap.put("U+1F3CD", "motorcycle");
			allEmojiMap.put("U+1F938", "person cartwheeling");
			allEmojiMap.put("U+1F938 U+200D U+2642 U+FE0F", "man cartwheeling");
			allEmojiMap.put("U+1F938 U+200D U+2640 U+FE0F", "woman cartwheeling");
			allEmojiMap.put("U+1F93C", "people wrestling");
			allEmojiMap.put("U+1F93C U+200D U+2642 U+FE0F", "men wrestling");
			allEmojiMap.put("U+1F93C U+200D U+2640 U+FE0F", "women wrestling");
			allEmojiMap.put("U+1F93D", "person playing water polo");
			allEmojiMap.put("U+1F93D U+200D U+2642 U+FE0F", "man playing water polo");
			allEmojiMap.put("U+1F93D U+200D U+2640 U+FE0F", "woman playing water polo");
			allEmojiMap.put("U+1F93E", "person playing handball");
			allEmojiMap.put("U+1F93E U+200D U+2642 U+FE0F", "man playing handball");
			allEmojiMap.put("U+1F93E U+200D U+2640 U+FE0F", "woman playing handball");
			allEmojiMap.put("U+1F939", "person juggling");
			allEmojiMap.put("U+1F939 U+200D U+2642 U+FE0F", "man juggling");
			allEmojiMap.put("U+1F939 U+200D U+2640 U+FE0F", "woman juggling");
			allEmojiMap.put("U+1F46B", "man and woman holding hands");
			allEmojiMap.put("U+1F46C", "two men holding hands");
			allEmojiMap.put("U+1F46D", "two women holding hands");
			allEmojiMap.put("U+1F48F", "kiss");
			allEmojiMap.put("U+1F491", "couple with heart");
			allEmojiMap.put("U+1F46A", "family");
			allEmojiMap.put("U+1F933", "selfie");
			allEmojiMap.put("U+1F4AA", "flexed biceps");
			allEmojiMap.put("U+1F448", "backhand index pointing left");
			allEmojiMap.put("U+1F449", "backhand index pointing right");
			allEmojiMap.put("U+261D", "index pointing up");
			allEmojiMap.put("U+1F446", "backhand index pointing up");
			allEmojiMap.put("U+1F595", "middle finger");
			allEmojiMap.put("U+1F447", "backhand index pointing down");
			allEmojiMap.put("U+270C", "victory hand");
			allEmojiMap.put("U+1F91E", "crossed fingers");
			allEmojiMap.put("U+1F596", "vulcan salute");
			allEmojiMap.put("U+1F918", "sign of the horns");
			allEmojiMap.put("U+1F919", "call me hand");
			allEmojiMap.put("U+1F590", "hand with fingers splayed");
			allEmojiMap.put("U+270B", "raised hand");
			allEmojiMap.put("U+1F44C", "OK hand");
			allEmojiMap.put("U+1F44D", "thumbs up");
			allEmojiMap.put("U+1F44E", "thumbs down");
			allEmojiMap.put("U+270A", "raised fist");
			allEmojiMap.put("U+1F44A", "oncoming fist");
			allEmojiMap.put("U+1F91B", "left-facing fist");
			allEmojiMap.put("U+1F91C", "right-facing fist");
			allEmojiMap.put("U+1F91A", "raised back of hand");
			allEmojiMap.put("U+1F44B", "waving hand");
			allEmojiMap.put("U+270D", "writing hand");
			allEmojiMap.put("U+1F44F", "clapping hands");
			allEmojiMap.put("U+1F450", "open hands");
			allEmojiMap.put("U+1F64C", "raising hands");
			allEmojiMap.put("U+1F64F", "folded hands");
			allEmojiMap.put("U+1F91D", "handshake");
			allEmojiMap.put("U+1F485", "nail polish");
			allEmojiMap.put("U+1F442", "ear");
			allEmojiMap.put("U+1F443", "nose");
			allEmojiMap.put("U+1F463", "footprints");
			allEmojiMap.put("U+1F440", "eyes");
			allEmojiMap.put("U+1F441", "eye");
			allEmojiMap.put("U+1F441 U+FE0F U+200D U+1F5E8 U+FE0F", "eye in speech bubble");
			allEmojiMap.put("U+1F445", "tongue");
			allEmojiMap.put("U+1F444", "mouth");
			allEmojiMap.put("U+1F48B", "kiss mark");
			allEmojiMap.put("U+1F498", "heart with arrow");
			allEmojiMap.put("U+2764", "red heart");
			allEmojiMap.put("U+1F493", "beating heart");
			allEmojiMap.put("U+1F494", "broken heart");
			allEmojiMap.put("U+1F495", "two hearts");
			allEmojiMap.put("U+1F496", "sparkling heart");
			allEmojiMap.put("U+1F497", "growing heart");
			allEmojiMap.put("U+1F499", "blue heart");
			allEmojiMap.put("U+1F49A", "green heart");
			allEmojiMap.put("U+1F49B", "yellow heart");
			allEmojiMap.put("U+1F49C", "purple heart");
			allEmojiMap.put("U+1F5A4", "black heart");
			allEmojiMap.put("U+1F49D", "heart with ribbon");
			allEmojiMap.put("U+1F49E", "revolving hearts");
			allEmojiMap.put("U+1F49F", "heart decoration");
			allEmojiMap.put("U+2763", "heavy heart exclamation");
			allEmojiMap.put("U+1F48C", "love letter");
			allEmojiMap.put("U+1F4A4", "zzz");
			allEmojiMap.put("U+1F4A2", "anger symbol");
			allEmojiMap.put("U+1F4A3", "bomb");
			allEmojiMap.put("U+1F4A5", "collision");
			allEmojiMap.put("U+1F4A6", "sweat droplets");
			allEmojiMap.put("U+1F4A8", "dashing away");
			allEmojiMap.put("U+1F4AB", "dizzy");
			allEmojiMap.put("U+1F4AC", "speech balloon");
			allEmojiMap.put("U+1F5E8", "left speech bubble");
			allEmojiMap.put("U+1F5EF", "right anger bubble");
			allEmojiMap.put("U+1F4AD", "thought balloon");
			allEmojiMap.put("U+1F573", "hole");
			allEmojiMap.put("U+1F453", "glasses");
			allEmojiMap.put("U+1F576", "sunglasses");
			allEmojiMap.put("U+1F454", "necktie");
			allEmojiMap.put("U+1F455", "t-shirt");
			allEmojiMap.put("U+1F456", "jeans");
			allEmojiMap.put("U+1F457", "dress");
			allEmojiMap.put("U+1F458", "kimono");
			allEmojiMap.put("U+1F459", "bikini");
			allEmojiMap.put("U+1F45B", "purse");
			allEmojiMap.put("U+1F45C", "handbag");
			allEmojiMap.put("U+1F45D", "clutch bag");
			allEmojiMap.put("U+1F6CD", "shopping bags");
			allEmojiMap.put("U+1F392", "school backpack");
			allEmojiMap.put("U+1F45F", "running shoe");
			allEmojiMap.put("U+1F460", "high-heeled shoe");
			allEmojiMap.put("U+1F451", "crown");
			allEmojiMap.put("U+1F3A9", "top hat");
			allEmojiMap.put("U+1F393", "graduation cap");
			allEmojiMap.put("U+1F4FF", "prayer beads");
			allEmojiMap.put("U+1F484", "lipstick");
			allEmojiMap.put("U+1F48D", "ring");
			allEmojiMap.put("U+1F48E", "gem stone");
			allEmojiMap.put("U+1F435", "monkey face");
			allEmojiMap.put("U+1F412", "monkey");
			allEmojiMap.put("U+1F98D", "gorilla");
			allEmojiMap.put("U+1F436", "dog face");
			allEmojiMap.put("U+1F415", "dog");
			allEmojiMap.put("U+1F429", "poodle");
			allEmojiMap.put("U+1F43A", "wolf face");
			allEmojiMap.put("U+1F98A", "fox face");
			allEmojiMap.put("U+1F431", "cat face");
			allEmojiMap.put("U+1F408", "cat");
			allEmojiMap.put("U+1F981", "lion face");
			allEmojiMap.put("U+1F42F", "tiger face");
			allEmojiMap.put("U+1F405", "tiger");
			allEmojiMap.put("U+1F406", "leopard");
			allEmojiMap.put("U+1F434", "horse face");
			allEmojiMap.put("U+1F40E", "horse");
			allEmojiMap.put("U+1F984", "unicorn face");
			allEmojiMap.put("U+1F98C", "deer");
			allEmojiMap.put("U+1F42E", "cow face");
			allEmojiMap.put("U+1F402", "ox");
			allEmojiMap.put("U+1F403", "water buffalo");
			allEmojiMap.put("U+1F404", "cow");
			allEmojiMap.put("U+1F437", "pig face");
			allEmojiMap.put("U+1F416", "pig");
			allEmojiMap.put("U+1F417", "boar");
			allEmojiMap.put("U+1F43D", "pig nose");
			allEmojiMap.put("U+1F40F", "ram");
			allEmojiMap.put("U+1F411", "ewe");
			allEmojiMap.put("U+1F410", "goat");
			allEmojiMap.put("U+1F42A", "camel");
			allEmojiMap.put("U+1F42B", "two-hump camel");
			allEmojiMap.put("U+1F418", "elephant");
			allEmojiMap.put("U+1F98F", "rhinoceros");
			allEmojiMap.put("U+1F42D", "mouse face");
			allEmojiMap.put("U+1F401", "mouse");
			allEmojiMap.put("U+1F400", "rat");
			allEmojiMap.put("U+1F439", "hamster face");
			allEmojiMap.put("U+1F430", "rabbit face");
			allEmojiMap.put("U+1F407", "rabbit");
			allEmojiMap.put("U+1F43F", "chipmunk");
			allEmojiMap.put("U+1F987", "bat");
			allEmojiMap.put("U+1F43B", "bear face");
			allEmojiMap.put("U+1F428", "koala");
			allEmojiMap.put("U+1F43C", "panda face");
			allEmojiMap.put("U+1F43E", "paw prints");
			allEmojiMap.put("U+1F983", "turkey");
			allEmojiMap.put("U+1F414", "chicken");
			allEmojiMap.put("U+1F413", "rooster");
			allEmojiMap.put("U+1F423", "hatching chick");
			allEmojiMap.put("U+1F424", "baby chick");
			allEmojiMap.put("U+1F425", "front-facing baby chick");
			allEmojiMap.put("U+1F426", "bird");
			allEmojiMap.put("U+1F427", "penguin");
			allEmojiMap.put("U+1F54A", "dove");
			allEmojiMap.put("U+1F985", "eagle");
			allEmojiMap.put("U+1F986", "duck");
			allEmojiMap.put("U+1F989", "owl");
			allEmojiMap.put("U+1F438", "frog face");
			allEmojiMap.put("U+1F40A", "crocodile");
			allEmojiMap.put("U+1F422", "turtle");
			allEmojiMap.put("U+1F98E", "lizard");
			allEmojiMap.put("U+1F40D", "snake");
			allEmojiMap.put("U+1F432", "dragon face");
			allEmojiMap.put("U+1F409", "dragon");
			allEmojiMap.put("U+1F433", "spouting whale");
			allEmojiMap.put("U+1F40B", "whale");
			allEmojiMap.put("U+1F42C", "dolphin");
			allEmojiMap.put("U+1F41F", "fish");
			allEmojiMap.put("U+1F420", "tropical fish");
			allEmojiMap.put("U+1F421", "blowfish");
			allEmojiMap.put("U+1F988", "shark");
			allEmojiMap.put("U+1F419", "octopus");
			allEmojiMap.put("U+1F41A", "spiral shell");
			allEmojiMap.put("U+1F980", "crab");
			allEmojiMap.put("U+1F990", "shrimp");
			allEmojiMap.put("U+1F991", "squid");
			allEmojiMap.put("U+1F40C", "snail");
			allEmojiMap.put("U+1F98B", "butterfly");
			allEmojiMap.put("U+1F41B", "bug");
			allEmojiMap.put("U+1F41C", "ant");
			allEmojiMap.put("U+1F41D", "honeybee");
			allEmojiMap.put("U+1F41E", "lady beetle");
			allEmojiMap.put("U+1F577", "spider");
			allEmojiMap.put("U+1F578", "spider web");
			allEmojiMap.put("U+1F982", "scorpion");
			allEmojiMap.put("U+1F490", "bouquet");
			allEmojiMap.put("U+1F338", "cherry blossom");
			allEmojiMap.put("U+1F4AE", "white flower");
			allEmojiMap.put("U+1F3F5", "rosette");
			allEmojiMap.put("U+1F339", "rose");
			allEmojiMap.put("U+1F940", "wilted flower");
			allEmojiMap.put("U+1F33A", "hibiscus");
			allEmojiMap.put("U+1F33B", "sunflower");
			allEmojiMap.put("U+1F33C", "blossom");
			allEmojiMap.put("U+1F337", "tulip");
			allEmojiMap.put("U+1F331", "seedling");
			allEmojiMap.put("U+1F332", "evergreen tree");
			allEmojiMap.put("U+1F333", "deciduous tree");
			allEmojiMap.put("U+1F334", "palm tree");
			allEmojiMap.put("U+1F335", "cactus");
			allEmojiMap.put("U+1F33E", "sheaf of rice");
			allEmojiMap.put("U+1F33F", "herb");
			allEmojiMap.put("U+2618", "shamrock");
			allEmojiMap.put("U+1F340", "four leaf clover");
			allEmojiMap.put("U+1F341", "maple leaf");
			allEmojiMap.put("U+1F342", "fallen leaf");
			allEmojiMap.put("U+1F343", "leaf fluttering in wind");
			allEmojiMap.put("U+1F347", "grapes");
			allEmojiMap.put("U+1F348", "melon");
			allEmojiMap.put("U+1F349", "watermelon");
			allEmojiMap.put("U+1F34A", "tangerine");
			allEmojiMap.put("U+1F34B", "lemon");
			allEmojiMap.put("U+1F34C", "banana");
			allEmojiMap.put("U+1F34D", "pineapple");
			allEmojiMap.put("U+1F34E", "red apple");
			allEmojiMap.put("U+1F34F", "green apple");
			allEmojiMap.put("U+1F350", "pear");
			allEmojiMap.put("U+1F351", "peach");
			allEmojiMap.put("U+1F352", "cherries");
			allEmojiMap.put("U+1F353", "strawberry");
			allEmojiMap.put("U+1F95D", "kiwi fruit");
			allEmojiMap.put("U+1F345", "tomato");
			allEmojiMap.put("U+1F951", "avocado");
			allEmojiMap.put("U+1F346", "eggplant");
			allEmojiMap.put("U+1F954", "potato");
			allEmojiMap.put("U+1F955", "carrot");
			allEmojiMap.put("U+1F33D", "ear of corn");
			allEmojiMap.put("U+1F336", "hot pepper");
			allEmojiMap.put("U+1F952", "cucumber");
			allEmojiMap.put("U+1F344", "mushroom");
			allEmojiMap.put("U+1F95C", "peanuts");
			allEmojiMap.put("U+1F330", "chestnut");
			allEmojiMap.put("U+1F35E", "bread");
			allEmojiMap.put("U+1F950", "croissant");
			allEmojiMap.put("U+1F956", "baguette bread");
			allEmojiMap.put("U+1F95E", "pancakes");
			allEmojiMap.put("U+1F9C0", "cheese wedge");
			allEmojiMap.put("U+1F356", "meat on bone");
			allEmojiMap.put("U+1F357", "poultry leg");
			allEmojiMap.put("U+1F953", "bacon");
			allEmojiMap.put("U+1F354", "hamburger");
			allEmojiMap.put("U+1F35F", "french fries");
			allEmojiMap.put("U+1F355", "pizza");
			allEmojiMap.put("U+1F32D", "hot dog");
			allEmojiMap.put("U+1F32E", "taco");
			allEmojiMap.put("U+1F32F", "burrito");
			allEmojiMap.put("U+1F959", "stuffed flatbread");
			allEmojiMap.put("U+1F95A", "egg");
			allEmojiMap.put("U+1F373", "cooking");
			allEmojiMap.put("U+1F958", "shallow pan of food");
			allEmojiMap.put("U+1F372", "pot of food");
			allEmojiMap.put("U+1F957", "green salad");
			allEmojiMap.put("U+1F37F", "popcorn");
			allEmojiMap.put("U+1F371", "bento box");
			allEmojiMap.put("U+1F358", "rice cracker");
			allEmojiMap.put("U+1F359", "rice ball");
			allEmojiMap.put("U+1F35A", "cooked rice");
			allEmojiMap.put("U+1F35B", "curry rice");
			allEmojiMap.put("U+1F35C", "steaming bowl");
			allEmojiMap.put("U+1F35D", "spaghetti");
			allEmojiMap.put("U+1F360", "roasted sweet potato");
			allEmojiMap.put("U+1F362", "oden");
			allEmojiMap.put("U+1F363", "sushi");
			allEmojiMap.put("U+1F364", "fried shrimp");
			allEmojiMap.put("U+1F365", "fish cake with swirl");
			allEmojiMap.put("U+1F361", "dango");
			allEmojiMap.put("U+1F366", "soft ice cream");
			allEmojiMap.put("U+1F367", "shaved ice");
			allEmojiMap.put("U+1F368", "ice cream");
			allEmojiMap.put("U+1F369", "doughnut");
			allEmojiMap.put("U+1F36A", "cookie");
			allEmojiMap.put("U+1F382", "birthday cake");
			allEmojiMap.put("U+1F370", "shortcake");
			allEmojiMap.put("U+1F36B", "chocolate bar");
			allEmojiMap.put("U+1F36C", "candy");
			allEmojiMap.put("U+1F36D", "lollipop");
			allEmojiMap.put("U+1F36E", "custard");
			allEmojiMap.put("U+1F36F", "honey pot");
			allEmojiMap.put("U+1F37C", "baby bottle");
			allEmojiMap.put("U+1F95B", "glass of milk");
			allEmojiMap.put("U+2615", "hot beverage");
			allEmojiMap.put("U+1F375", "teacup without handle");
			allEmojiMap.put("U+1F376", "sake");
			allEmojiMap.put("U+1F37E", "bottle with popping cork");
			allEmojiMap.put("U+1F377", "wine glass");
			allEmojiMap.put("U+1F378", "cocktail glass");
			allEmojiMap.put("U+1F379", "tropical drink");
			allEmojiMap.put("U+1F37A", "beer mug");
			allEmojiMap.put("U+1F37B", "clinking beer mugs");
			allEmojiMap.put("U+1F942", "clinking glasses");
			allEmojiMap.put("U+1F943", "tumbler glass");
			allEmojiMap.put("U+1F37D", "fork and knife with plate");
			allEmojiMap.put("U+1F374", "fork and knife");
			allEmojiMap.put("U+1F944", "spoon");
			allEmojiMap.put("U+1F52A", "kitchen knife");
			allEmojiMap.put("U+1F3FA", "amphora");
			allEmojiMap.put("U+1F30D", "globe showing Europe-Africa");
			allEmojiMap.put("U+1F30E", "globe showing Americas");
			allEmojiMap.put("U+1F30F", "globe showing Asia-Australia");
			allEmojiMap.put("U+1F310", "globe with meridians");
			allEmojiMap.put("U+1F5FA", "world map");
			allEmojiMap.put("U+1F5FE", "map of Japan");
			allEmojiMap.put("U+1F3D4", "snow-capped mountain");
			allEmojiMap.put("U+26F0", "mountain");
			allEmojiMap.put("U+1F30B", "volcano");
			allEmojiMap.put("U+1F5FB", "mount fuji");
			allEmojiMap.put("U+1F3D5", "camping");
			allEmojiMap.put("U+1F3D6", "beach with umbrella");
			allEmojiMap.put("U+1F3DC", "desert");
			allEmojiMap.put("U+1F3DD", "desert island");
			allEmojiMap.put("U+1F3DE", "national park");
			allEmojiMap.put("U+1F3DF", "stadium");
			allEmojiMap.put("U+1F3DB", "classical building");
			allEmojiMap.put("U+1F3D7", "building construction");
			allEmojiMap.put("U+1F3D8", "houses");
			allEmojiMap.put("U+1F3D9", "cityscape");
			allEmojiMap.put("U+1F3DA", "derelict house");
			allEmojiMap.put("U+1F3E0", "house");
			allEmojiMap.put("U+1F3E1", "house with garden");
			allEmojiMap.put("U+1F3E2", "office building");
			allEmojiMap.put("U+1F3E3", "Japanese post office");
			allEmojiMap.put("U+1F3E4", "post office");
			allEmojiMap.put("U+1F3E5", "hospital");
			allEmojiMap.put("U+1F3E6", "bank");
			allEmojiMap.put("U+1F3E8", "hotel");
			allEmojiMap.put("U+1F3E9", "love hotel");
			allEmojiMap.put("U+1F3EA", "convenience store");
			allEmojiMap.put("U+1F3EB", "school");
			allEmojiMap.put("U+1F3EC", "department store");
			allEmojiMap.put("U+1F3ED", "factory");
			allEmojiMap.put("U+1F3EF", "Japanese castle");
			allEmojiMap.put("U+1F3F0", "castle");
			allEmojiMap.put("U+1F492", "wedding");
			allEmojiMap.put("U+1F5FC", "Tokyo tower");
			allEmojiMap.put("U+1F5FD", "Statue of Liberty");
			allEmojiMap.put("U+26EA", "church");
			allEmojiMap.put("U+1F54C", "mosque");
			allEmojiMap.put("U+1F54D", "synagogue");
			allEmojiMap.put("U+26E9", "shinto shrine");
			allEmojiMap.put("U+1F54B", "kaaba");
			allEmojiMap.put("U+26F2", "fountain");
			allEmojiMap.put("U+26FA", "tent");
			allEmojiMap.put("U+1F301", "foggy");
			allEmojiMap.put("U+1F303", "night with stars");
			allEmojiMap.put("U+1F304", "sunrise over mountains");
			allEmojiMap.put("U+1F305", "sunrise");
			allEmojiMap.put("U+1F306", "cityscape at dusk");
			allEmojiMap.put("U+1F307", "sunset");
			allEmojiMap.put("U+1F309", "bridge at night");
			allEmojiMap.put("U+2668", "hot springs");
			allEmojiMap.put("U+1F30C", "milky way");
			allEmojiMap.put("U+1F3A0", "carousel horse");
			allEmojiMap.put("U+1F3A1", "ferris wheel");
			allEmojiMap.put("U+1F3A2", "roller coaster");
			allEmojiMap.put("U+1F488", "barber pole");
			allEmojiMap.put("U+1F3AA", "circus tent");
			allEmojiMap.put("U+1F3AD", "performing arts");
			allEmojiMap.put("U+1F5BC", "framed picture");
			allEmojiMap.put("U+1F3A8", "artist palette");
			allEmojiMap.put("U+1F3B0", "slot machine");
			allEmojiMap.put("U+1F682", "locomotive");
			allEmojiMap.put("U+1F683", "railway car");
			allEmojiMap.put("U+1F684", "high-speed train");
			allEmojiMap.put("U+1F685", "bullet train");
			allEmojiMap.put("U+1F686", "train");
			allEmojiMap.put("U+1F687", "metro");
			allEmojiMap.put("U+1F688", "light rail");
			allEmojiMap.put("U+1F689", "station");
			allEmojiMap.put("U+1F68A", "tram");
			allEmojiMap.put("U+1F69D", "monorail");
			allEmojiMap.put("U+1F69E", "mountain railway");
			allEmojiMap.put("U+1F68B", "tram car");
			allEmojiMap.put("U+1F68C", "bus");
			allEmojiMap.put("U+1F68D", "oncoming bus");
			allEmojiMap.put("U+1F68E", "trolleybus");
			allEmojiMap.put("U+1F690", "minibus");
			allEmojiMap.put("U+1F691", "ambulance");
			allEmojiMap.put("U+1F692", "fire engine");
			allEmojiMap.put("U+1F693", "police car");
			allEmojiMap.put("U+1F694", "oncoming police car");
			allEmojiMap.put("U+1F695", "taxi");
			allEmojiMap.put("U+1F696", "oncoming taxi");
			allEmojiMap.put("U+1F697", "automobile");
			allEmojiMap.put("U+1F698", "oncoming automobile");
			allEmojiMap.put("U+1F699", "sport utility vehicle");
			allEmojiMap.put("U+1F69A", "delivery truck");
			allEmojiMap.put("U+1F69B", "articulated lorry");
			allEmojiMap.put("U+1F69C", "tractor");
			allEmojiMap.put("U+1F6B2", "bicycle");
			allEmojiMap.put("U+1F6F4", "kick scooter");
			allEmojiMap.put("U+1F6F5", "motor scooter");
			allEmojiMap.put("U+1F68F", "bus stop");
			allEmojiMap.put("U+1F6E3", "motorway");
			allEmojiMap.put("U+1F6E4", "railway track");
			allEmojiMap.put("U+26FD", "fuel pump");
			allEmojiMap.put("U+1F6A8", "police car light");
			allEmojiMap.put("U+1F6A5", "horizontal traffic light");
			allEmojiMap.put("U+1F6A6", "vertical traffic light");
			allEmojiMap.put("U+1F6A7", "construction");
			allEmojiMap.put("U+1F6D1", "stop sign");
			allEmojiMap.put("U+2693", "anchor");
			allEmojiMap.put("U+26F5", "sailboat");
			allEmojiMap.put("U+1F6F6", "canoe");
			allEmojiMap.put("U+1F6A4", "speedboat");
			allEmojiMap.put("U+1F6F3", "passenger ship");
			allEmojiMap.put("U+26F4", "ferry");
			allEmojiMap.put("U+1F6E5", "motor boat");
			allEmojiMap.put("U+1F6A2", "ship");
			allEmojiMap.put("U+2708", "airplane");
			allEmojiMap.put("U+1F6E9", "small airplane");
			allEmojiMap.put("U+1F6EB", "airplane departure");
			allEmojiMap.put("U+1F6EC", "airplane arrival");
			allEmojiMap.put("U+1F4BA", "seat");
			allEmojiMap.put("U+1F681", "helicopter");
			allEmojiMap.put("U+1F69F", "suspension railway");
			allEmojiMap.put("U+1F6A0", "mountain cableway");
			allEmojiMap.put("U+1F6A1", "aerial tramway");
			allEmojiMap.put("U+1F6F0", "satellite");
			allEmojiMap.put("U+1F680", "rocket");
			allEmojiMap.put("U+1F6CE", "bellhop bell");
			allEmojiMap.put("U+1F6AA", "door");
			allEmojiMap.put("U+1F6CF", "bed");
			allEmojiMap.put("U+1F6CB", "couch and lamp");
			allEmojiMap.put("U+1F6BD", "toilet");
			allEmojiMap.put("U+1F6BF", "shower");
			allEmojiMap.put("U+1F6C1", "bathtub");
			allEmojiMap.put("U+231B", "hourglass done");
			allEmojiMap.put("U+23F3", "hourglass not done");
			allEmojiMap.put("U+231A", "watch");
			allEmojiMap.put("U+23F0", "alarm clock");
			allEmojiMap.put("U+23F1", "stopwatch");
			allEmojiMap.put("U+23F2", "timer clock");
			allEmojiMap.put("U+1F570", "mantelpiece clock");
			allEmojiMap.put("U+1F567", "twelve-thirty");
			allEmojiMap.put("U+1F55C", "one-thirty");
			allEmojiMap.put("U+1F55D", "two-thirty");
			allEmojiMap.put("U+1F55E", "three-thirty");
			allEmojiMap.put("U+1F55F", "four-thirty");
			allEmojiMap.put("U+1F560", "five-thirty");
			allEmojiMap.put("U+1F561", "six-thirty");
			allEmojiMap.put("U+1F562", "seven-thirty");
			allEmojiMap.put("U+1F563", "eight-thirty");
			allEmojiMap.put("U+1F564", "nine-thirty");
			allEmojiMap.put("U+1F565", "ten-thirty");
			allEmojiMap.put("U+1F566", "eleven-thirty");
			allEmojiMap.put("U+1F311", "new moon");
			allEmojiMap.put("U+1F312", "waxing crescent moon");
			allEmojiMap.put("U+1F313", "first quarter moon");
			allEmojiMap.put("U+1F314", "waxing gibbous moon");
			allEmojiMap.put("U+1F315", "full moon");
			allEmojiMap.put("U+1F316", "waning gibbous moon");
			allEmojiMap.put("U+1F317", "last quarter moon");
			allEmojiMap.put("U+1F318", "waning crescent moon");
			allEmojiMap.put("U+1F319", "crescent moon");
			allEmojiMap.put("U+1F31A", "new moon face");
			allEmojiMap.put("U+1F31B", "first quarter moon face");
			allEmojiMap.put("U+1F31C", "last quarter moon face");
			allEmojiMap.put("U+1F321", "thermometer");
			allEmojiMap.put("U+2600", "sun");
			allEmojiMap.put("U+1F31D", "full moon face");
			allEmojiMap.put("U+1F31E", "sun with face");
			allEmojiMap.put("U+2B50", "white medium star");
			allEmojiMap.put("U+1F31F", "glowing star");
			allEmojiMap.put("U+1F320", "shooting star");
			allEmojiMap.put("U+2601", "cloud");
			allEmojiMap.put("U+26C5", "sun behind cloud");
			allEmojiMap.put("U+26C8", "cloud with lightning and rain");
			allEmojiMap.put("U+1F324", "sun behind small cloud");
			allEmojiMap.put("U+1F325", "sun behind large cloud");
			allEmojiMap.put("U+1F326", "sun behind rain cloud");
			allEmojiMap.put("U+1F327", "cloud with rain");
			allEmojiMap.put("U+1F328", "cloud with snow");
			allEmojiMap.put("U+1F329", "cloud with lightning");
			allEmojiMap.put("U+1F32A", "tornado");
			allEmojiMap.put("U+1F32B", "fog");
			allEmojiMap.put("U+1F32C", "wind face");
			allEmojiMap.put("U+1F300", "cyclone");
			allEmojiMap.put("U+1F308", "rainbow");
			allEmojiMap.put("U+1F302", "closed umbrella");
			allEmojiMap.put("U+2602", "umbrella");
			allEmojiMap.put("U+2614", "umbrella with rain drops");
			allEmojiMap.put("U+26F1", "umbrella on ground");
			allEmojiMap.put("U+26A1", "high voltage");
			allEmojiMap.put("U+2744", "snowflake");
			allEmojiMap.put("U+2603", "snowman");
			allEmojiMap.put("U+26C4", "snowman without snow");
			allEmojiMap.put("U+2604", "comet");
			allEmojiMap.put("U+1F525", "fire");
			allEmojiMap.put("U+1F4A7", "droplet");
			allEmojiMap.put("U+1F30A", "water wave");
			allEmojiMap.put("U+1F383", "jack-o-lantern");
			allEmojiMap.put("U+1F384", "Christmas tree");
			allEmojiMap.put("U+1F386", "fireworks");
			allEmojiMap.put("U+1F387", "sparkler");
			allEmojiMap.put("U+2728", "sparkles");
			allEmojiMap.put("U+1F388", "balloon");
			allEmojiMap.put("U+1F389", "party popper");
			allEmojiMap.put("U+1F38A", "confetti ball");
			allEmojiMap.put("U+1F38B", "tanabata tree");
			allEmojiMap.put("U+1F38D", "pine decoration");
			allEmojiMap.put("U+1F38E", "Japanese dolls");
			allEmojiMap.put("U+1F38F", "carp streamer");
			allEmojiMap.put("U+1F390", "wind chime");
			allEmojiMap.put("U+1F391", "moon viewing ceremony");
			allEmojiMap.put("U+1F380", "ribbon");
			allEmojiMap.put("U+1F381", "wrapped gift");
			allEmojiMap.put("U+1F397", "reminder ribbon");
			allEmojiMap.put("U+1F39F", "admission tickets");
			allEmojiMap.put("U+1F3AB", "ticket");
			allEmojiMap.put("U+1F396", "military medal");
			allEmojiMap.put("U+1F3C6", "trophy");
			allEmojiMap.put("U+1F3C5", "sports medal");
			allEmojiMap.put("U+1F947", "1st place medal");
			allEmojiMap.put("U+1F948", "2nd place medal");
			allEmojiMap.put("U+1F949", "3rd place medal");
			allEmojiMap.put("U+26BD", "soccer ball");
			allEmojiMap.put("U+26BE", "baseball");
			allEmojiMap.put("U+1F3C0", "basketball");
			allEmojiMap.put("U+1F3D0", "volleyball");
			allEmojiMap.put("U+1F3C8", "american football");
			allEmojiMap.put("U+1F3C9", "rugby football");
			allEmojiMap.put("U+1F3BE", "tennis");
			allEmojiMap.put("U+1F3B1", "pool 8 ball");
			allEmojiMap.put("U+1F3B3", "bowling");
			allEmojiMap.put("U+1F3CF", "cricket game");
			allEmojiMap.put("U+1F3D1", "field hockey");
			allEmojiMap.put("U+1F3D2", "ice hockey");
			allEmojiMap.put("U+1F3D3", "ping pong");
			allEmojiMap.put("U+1F3F8", "badminton");
			allEmojiMap.put("U+1F94A", "boxing glove");
			allEmojiMap.put("U+1F94B", "martial arts uniform");
			allEmojiMap.put("U+1F945", "goal net");
			allEmojiMap.put("U+1F3AF", "direct hit");
			allEmojiMap.put("U+26F3", "flag in hole");
			allEmojiMap.put("U+26F8", "ice skate");
			allEmojiMap.put("U+1F3A3", "fishing pole");
			allEmojiMap.put("U+1F3BD", "running shirt");
			allEmojiMap.put("U+1F3BF", "skis");
			allEmojiMap.put("U+1F3AE", "video game");
			allEmojiMap.put("U+1F579", "joystick");
			allEmojiMap.put("U+1F3B2", "game die");
			allEmojiMap.put("U+2660", "spade suit");
			allEmojiMap.put("U+2665", "heart suit");
			allEmojiMap.put("U+2666", "diamond suit");
			allEmojiMap.put("U+2663", "club suit");
			allEmojiMap.put("U+1F0CF", "joker");
			allEmojiMap.put("U+1F004", "mahjong red dragon");
			allEmojiMap.put("U+1F3B4", "flower playing cards");
			allEmojiMap.put("U+1F507", "muted speaker");
			allEmojiMap.put("U+1F508", "speaker low volume");
			allEmojiMap.put("U+1F509", "speaker medium volume");
			allEmojiMap.put("U+1F50A", "speaker high volume");
			allEmojiMap.put("U+1F4E2", "loudspeaker");
			allEmojiMap.put("U+1F4E3", "megaphone");
			allEmojiMap.put("U+1F4EF", "postal horn");
			allEmojiMap.put("U+1F514", "bell");
			allEmojiMap.put("U+1F515", "bell with slash");
			allEmojiMap.put("U+1F3BC", "musical score");
			allEmojiMap.put("U+1F3B5", "musical note");
			allEmojiMap.put("U+1F3B6", "musical notes");
			allEmojiMap.put("U+1F399", "studio microphone");
			allEmojiMap.put("U+1F39A", "level slider");
			allEmojiMap.put("U+1F39B", "control knobs");
			allEmojiMap.put("U+1F3A4", "microphone");
			allEmojiMap.put("U+1F3A7", "headphone");
			allEmojiMap.put("U+1F4FB", "radio");
			allEmojiMap.put("U+1F3B7", "saxophone");
			allEmojiMap.put("U+1F3B8", "guitar");
			allEmojiMap.put("U+1F3B9", "musical keyboard");
			allEmojiMap.put("U+1F3BA", "trumpet");
			allEmojiMap.put("U+1F3BB", "violin");
			allEmojiMap.put("U+1F941", "drum");
			allEmojiMap.put("U+1F4F1", "mobile phone");
			allEmojiMap.put("U+1F4F2", "mobile phone with arrow");
			allEmojiMap.put("U+260E", "telephone");
			allEmojiMap.put("U+1F4DE", "telephone receiver");
			allEmojiMap.put("U+1F4DF", "pager");
			allEmojiMap.put("U+1F4E0", "fax machine");
			allEmojiMap.put("U+1F50B", "battery");
			allEmojiMap.put("U+1F50C", "electric plug");
			allEmojiMap.put("U+1F4BB", "laptop computer");
			allEmojiMap.put("U+1F5A5", "desktop computer");
			allEmojiMap.put("U+1F5A8", "printer");
			allEmojiMap.put("U+2328", "keyboard");
			allEmojiMap.put("U+1F5B1", "computer mouse");
			allEmojiMap.put("U+1F5B2", "trackball");
			allEmojiMap.put("U+1F4BD", "computer disk");
			allEmojiMap.put("U+1F4BE", "floppy disk");
			allEmojiMap.put("U+1F4BF", "optical disk");
			allEmojiMap.put("U+1F4C0", "dvd");
			allEmojiMap.put("U+1F3A5", "movie camera");
			allEmojiMap.put("U+1F39E", "film frames");
			allEmojiMap.put("U+1F4FD", "film projector");
			allEmojiMap.put("U+1F3AC", "clapper board");
			allEmojiMap.put("U+1F4FA", "television");
			allEmojiMap.put("U+1F4F7", "camera");
			allEmojiMap.put("U+1F4F8", "camera with flash");
			allEmojiMap.put("U+1F4F9", "video camera");
			allEmojiMap.put("U+1F4FC", "videocassette");
			allEmojiMap.put("U+1F50D", "magnifying glass tilted left");
			allEmojiMap.put("U+1F50E", "magnifying glass tilted right");
			allEmojiMap.put("U+1F52C", "microscope");
			allEmojiMap.put("U+1F52D", "telescope");
			allEmojiMap.put("U+1F4E1", "satellite antenna");
			allEmojiMap.put("U+1F56F", "candle");
			allEmojiMap.put("U+1F4A1", "light bulb");
			allEmojiMap.put("U+1F526", "flashlight");
			allEmojiMap.put("U+1F3EE", "red paper lantern");
			allEmojiMap.put("U+1F4D4", "notebook with decorative cover");
			allEmojiMap.put("U+1F4D5", "closed book");
			allEmojiMap.put("U+1F4D6", "open book");
			allEmojiMap.put("U+1F4D7", "green book");
			allEmojiMap.put("U+1F4D8", "blue book");
			allEmojiMap.put("U+1F4D9", "orange book");
			allEmojiMap.put("U+1F4DA", "books");
			allEmojiMap.put("U+1F4D3", "notebook");
			allEmojiMap.put("U+1F4D2", "ledger");
			allEmojiMap.put("U+1F4C3", "page with curl");
			allEmojiMap.put("U+1F4DC", "scroll");
			allEmojiMap.put("U+1F4C4", "page facing up");
			allEmojiMap.put("U+1F4F0", "newspaper");
			allEmojiMap.put("U+1F5DE", "rolled-up newspaper");
			allEmojiMap.put("U+1F4D1", "bookmark tabs");
			allEmojiMap.put("U+1F516", "bookmark");
			allEmojiMap.put("U+1F3F7", "label");
			allEmojiMap.put("U+1F4B0", "money bag");
			allEmojiMap.put("U+1F4B4", "yen banknote");
			allEmojiMap.put("U+1F4B5", "dollar banknote");
			allEmojiMap.put("U+1F4B6", "euro banknote");
			allEmojiMap.put("U+1F4B7", "pound banknote");
			allEmojiMap.put("U+1F4B8", "money with wings");
			allEmojiMap.put("U+1F4B3", "credit card");
			allEmojiMap.put("U+1F4B9", "chart increasing with yen");
			allEmojiMap.put("U+1F4B1", "currency exchange");
			allEmojiMap.put("U+1F4B2", "heavy dollar sign");
			allEmojiMap.put("U+2709", "envelope");
			allEmojiMap.put("U+1F4E7", "e-mail");
			allEmojiMap.put("U+1F4E8", "incoming envelope");
			allEmojiMap.put("U+1F4E9", "envelope with arrow");
			allEmojiMap.put("U+1F4E4", "outbox tray");
			allEmojiMap.put("U+1F4E5", "inbox tray");
			allEmojiMap.put("U+1F4E6", "package");
			allEmojiMap.put("U+1F4EB", "closed mailbox with raised flag");
			allEmojiMap.put("U+1F4EA", "closed mailbox with lowered flag");
			allEmojiMap.put("U+1F4EC", "open mailbox with raised flag");
			allEmojiMap.put("U+1F4ED", "open mailbox with lowered flag");
			allEmojiMap.put("U+1F4EE", "postbox");
			allEmojiMap.put("U+1F5F3", "ballot box with ballot");
			allEmojiMap.put("U+270F", "pencil");
			allEmojiMap.put("U+2712", "black nib");
			allEmojiMap.put("U+1F58B", "fountain pen");
			allEmojiMap.put("U+1F58A", "pen");
			allEmojiMap.put("U+1F58C", "paintbrush");
			allEmojiMap.put("U+1F58D", "crayon");
			allEmojiMap.put("U+1F4DD", "memo");
			allEmojiMap.put("U+1F4BC", "briefcase");
			allEmojiMap.put("U+1F4C1", "file folder");
			allEmojiMap.put("U+1F4C2", "open file folder");
			allEmojiMap.put("U+1F5C2", "card index dividers");
			allEmojiMap.put("U+1F4C5", "calendar");
			allEmojiMap.put("U+1F4C6", "tear-off calendar");
			allEmojiMap.put("U+1F5D2", "spiral notepad");
			allEmojiMap.put("U+1F5D3", "spiral calendar");
			allEmojiMap.put("U+1F4C7", "card index");
			allEmojiMap.put("U+1F4C8", "chart increasing");
			allEmojiMap.put("U+1F4C9", "chart decreasing");
			allEmojiMap.put("U+1F4CA", "bar chart");
			allEmojiMap.put("U+1F4CB", "clipboard");
			allEmojiMap.put("U+1F4CC", "pushpin");
			allEmojiMap.put("U+1F4CD", "round pushpin");
			allEmojiMap.put("U+1F4CE", "paperclip");
			allEmojiMap.put("U+1F587", "linked paperclips");
			allEmojiMap.put("U+1F4CF", "straight ruler");
			allEmojiMap.put("U+1F4D0", "triangular ruler");
			allEmojiMap.put("U+2702", "scissors");
			allEmojiMap.put("U+1F5C3", "card file box");
			allEmojiMap.put("U+1F5C4", "file cabinet");
			allEmojiMap.put("U+1F5D1", "wastebasket");
			allEmojiMap.put("U+1F512", "locked");
			allEmojiMap.put("U+1F513", "unlocked");
			allEmojiMap.put("U+1F50F", "locked with pen");
			allEmojiMap.put("U+1F510", "locked with key");
			allEmojiMap.put("U+1F511", "key");
			allEmojiMap.put("U+1F5DD", "old key");
			allEmojiMap.put("U+1F528", "hammer");
			allEmojiMap.put("U+26CF", "pick");
			allEmojiMap.put("U+2692", "hammer and pick");
			allEmojiMap.put("U+1F6E0", "hammer and wrench");
			allEmojiMap.put("U+1F5E1", "dagger");
			allEmojiMap.put("U+2694", "crossed swords");
			allEmojiMap.put("U+1F52B", "pistol");
			allEmojiMap.put("U+1F3F9", "bow and arrow");
			allEmojiMap.put("U+1F6E1", "shield");
			allEmojiMap.put("U+1F527", "wrench");
			allEmojiMap.put("U+1F529", "nut and bolt");
			allEmojiMap.put("U+2699", "gear");
			allEmojiMap.put("U+1F5DC", "clamp");
			allEmojiMap.put("U+2697", "alembic");
			allEmojiMap.put("U+2696", "balance scale");
			allEmojiMap.put("U+1F517", "link");
			allEmojiMap.put("U+26D3", "chains");
			allEmojiMap.put("U+1F489", "syringe");
			allEmojiMap.put("U+1F48A", "pill");
			allEmojiMap.put("U+1F6AC", "cigarette");
			allEmojiMap.put("U+26B0", "coffin");
			allEmojiMap.put("U+26B1", "funeral urn");
			allEmojiMap.put("U+1F5FF", "moai");
			allEmojiMap.put("U+1F6E2", "oil drum");
			allEmojiMap.put("U+1F52E", "crystal ball");
			allEmojiMap.put("U+1F6D2", "shopping cart");
			allEmojiMap.put("U+1F3E7", "ATM sign");
			allEmojiMap.put("U+1F6AE", "litter in bin sign");
			allEmojiMap.put("U+1F6B0", "potable water");
			allEmojiMap.put("U+267F", "wheelchair symbol");
			allEmojiMap.put("U+1F6BB", "restroom");
			allEmojiMap.put("U+1F6BC", "baby symbol");
			allEmojiMap.put("U+1F6BE", "water closet");
			allEmojiMap.put("U+1F6C2", "passport control");
			allEmojiMap.put("U+1F6C3", "customs");
			allEmojiMap.put("U+1F6C4", "baggage claim");
			allEmojiMap.put("U+1F6C5", "left luggage");
			allEmojiMap.put("U+26A0", "warning");
			allEmojiMap.put("U+1F6B8", "children crossing");
			allEmojiMap.put("U+26D4", "no entry");
			allEmojiMap.put("U+1F6AB", "prohibited");
			allEmojiMap.put("U+1F6B3", "no bicycles");
			allEmojiMap.put("U+1F6AD", "no smoking");
			allEmojiMap.put("U+1F6AF", "no littering");
			allEmojiMap.put("U+1F6B1", "non-potable water");
			allEmojiMap.put("U+1F6B7", "no pedestrians");
			allEmojiMap.put("U+1F4F5", "no mobile phones");
			allEmojiMap.put("U+1F51E", "no one under eighteen");
			allEmojiMap.put("U+2622", "radioactive");
			allEmojiMap.put("U+2623", "biohazard");
			allEmojiMap.put("U+2B06", "up arrow");
			allEmojiMap.put("U+2197", "up-right arrow");
			allEmojiMap.put("U+27A1", "right arrow");
			allEmojiMap.put("U+2198", "down-right arrow");
			allEmojiMap.put("U+2B07", "down arrow");
			allEmojiMap.put("U+2199", "down-left arrow");
			allEmojiMap.put("U+2B05", "left arrow");
			allEmojiMap.put("U+2196", "up-left arrow");
			allEmojiMap.put("U+2195", "up-down arrow");
			allEmojiMap.put("U+2194", "left-right arrow");
			allEmojiMap.put("U+21A9", "right arrow curving left");
			allEmojiMap.put("U+21AA", "left arrow curving right");
			allEmojiMap.put("U+2934", "right arrow curving up");
			allEmojiMap.put("U+2935", "right arrow curving down");
			allEmojiMap.put("U+1F503", "clockwise vertical arrows");
			allEmojiMap.put("U+1F504", "counterclockwise arrows button");
			allEmojiMap.put("U+1F519", "BACK arrow");
			allEmojiMap.put("U+1F51A", "END arrow");
			allEmojiMap.put("U+1F51C", "SOON arrow");
			allEmojiMap.put("U+1F51D", "TOP arrow");
			allEmojiMap.put("U+1F6D0", "place of worship");
			allEmojiMap.put("U+269B", "atom symbol");
			allEmojiMap.put("U+1F549", "om");
			allEmojiMap.put("U+2721", "star of David");
			allEmojiMap.put("U+2638", "wheel of dharma");
			allEmojiMap.put("U+262F", "yin yang");
			allEmojiMap.put("U+271D", "latin cross");
			allEmojiMap.put("U+2626", "orthodox cross");
			allEmojiMap.put("U+262A", "star and crescent");
			allEmojiMap.put("U+262E", "peace symbol");
			allEmojiMap.put("U+1F54E", "menorah");
			allEmojiMap.put("U+1F52F", "dotted six-pointed star");
			allEmojiMap.put("U+2648", "Aries");
			allEmojiMap.put("U+2649", "Taurus");
			allEmojiMap.put("U+264A", "Gemini");
			allEmojiMap.put("U+264B", "Cancer");
			allEmojiMap.put("U+264C", "Leo");
			allEmojiMap.put("U+264D", "Virgo");
			allEmojiMap.put("U+264E", "Libra");
			allEmojiMap.put("U+264F", "Scorpius");
			allEmojiMap.put("U+2650", "Sagittarius");
			allEmojiMap.put("U+2651", "Capricorn");
			allEmojiMap.put("U+2652", "Aquarius");
			allEmojiMap.put("U+2653", "Pisces");
			allEmojiMap.put("U+26CE", "Ophiuchus");
			allEmojiMap.put("U+1F500", "shuffle tracks button");
			allEmojiMap.put("U+1F501", "repeat button");
			allEmojiMap.put("U+1F502", "repeat single button");
			allEmojiMap.put("U+25B6", "play button");
			allEmojiMap.put("U+23E9", "fast-forward button");
			allEmojiMap.put("U+23ED", "next track button");
			allEmojiMap.put("U+23EF", "play or pause button");
			allEmojiMap.put("U+25C0", "reverse button");
			allEmojiMap.put("U+23EA", "fast reverse button");
			allEmojiMap.put("U+23EE", "last track button");
			allEmojiMap.put("U+1F53C", "up button");
			allEmojiMap.put("U+23EB", "fast up button");
			allEmojiMap.put("U+1F53D", "down button");
			allEmojiMap.put("U+23EC", "fast down button");
			allEmojiMap.put("U+23F8", "pause button");
			allEmojiMap.put("U+23F9", "stop button");
			allEmojiMap.put("U+23FA", "record button");
			allEmojiMap.put("U+23CF", "eject button");
			allEmojiMap.put("U+1F3A6", "cinema");
			allEmojiMap.put("U+1F505", "dim button");
			allEmojiMap.put("U+1F506", "bright button");
			allEmojiMap.put("U+1F4F6", "antenna bars");
			allEmojiMap.put("U+1F4F3", "vibration mode");
			allEmojiMap.put("U+1F4F4", "mobile phone off");
			allEmojiMap.put("U+2640", "female sign");
			allEmojiMap.put("U+2642", "male sign");
			allEmojiMap.put("U+2695", "medical symbol");
			allEmojiMap.put("U+267B", "recycling symbol");
			allEmojiMap.put("U+269C", "fleur-de-lis");
			allEmojiMap.put("U+1F531", "trident emblem");
			allEmojiMap.put("U+1F4DB", "name badge");
			allEmojiMap.put("U+1F530", "Japanese symbol for beginner");
			allEmojiMap.put("U+2B55", "heavy large circle");
			allEmojiMap.put("U+2705", "white heavy check mark");
			allEmojiMap.put("U+2611", "ballot box with check");
			allEmojiMap.put("U+2714", "heavy check mark");
			allEmojiMap.put("U+2716", "heavy multiplication x");
			allEmojiMap.put("U+274C", "cross mark");
			allEmojiMap.put("U+274E", "cross mark button");
			allEmojiMap.put("U+2795", "heavy plus sign");
			allEmojiMap.put("U+2796", "heavy minus sign");
			allEmojiMap.put("U+2797", "heavy division sign");
			allEmojiMap.put("U+27B0", "curly loop");
			allEmojiMap.put("U+27BF", "double curly loop");
			allEmojiMap.put("U+303D", "part alternation mark");
			allEmojiMap.put("U+2733", "eight-spoked asterisk");
			allEmojiMap.put("U+2734", "eight-pointed star");
			allEmojiMap.put("U+2747", "sparkle");
			allEmojiMap.put("U+203C", "double exclamation mark");
			allEmojiMap.put("U+2049", "exclamation question mark");
			allEmojiMap.put("U+2753", "question mark");
			allEmojiMap.put("U+2754", "white question mark");
			allEmojiMap.put("U+2755", "white exclamation mark");
			allEmojiMap.put("U+2757", "exclamation mark");
			allEmojiMap.put("U+3030", "wavy dash");
			allEmojiMap.put("U+00A9", "copyright");
			allEmojiMap.put("U+00AE", "registered");
			allEmojiMap.put("U+2122", "trade mark");
			allEmojiMap.put("U+1F51F", "keycap 10");
			allEmojiMap.put("U+1F4AF", "hundred points");
			allEmojiMap.put("U+1F520", "input latin uppercase");
			allEmojiMap.put("U+1F521", "input latin lowercase");
			allEmojiMap.put("U+1F522", "input numbers");
			allEmojiMap.put("U+1F523", "input symbols");
			allEmojiMap.put("U+1F524", "input latin letters");
			allEmojiMap.put("U+1F191", "CL button");
			allEmojiMap.put("U+1F192", "COOL button");
			allEmojiMap.put("U+1F193", "FREE button");
			allEmojiMap.put("U+2139", "information");
			allEmojiMap.put("U+1F194", "ID button");
			allEmojiMap.put("U+24C2", "circled M");
			allEmojiMap.put("U+1F195", "NEW button");
			allEmojiMap.put("U+1F196", "NG button");
			allEmojiMap.put("U+1F197", "OK button");
			allEmojiMap.put("U+1F17F", "P button");
			allEmojiMap.put("U+1F198", "SOS button");
			allEmojiMap.put("U+1F19A", "VS button");
			allEmojiMap.put("U+25AA", "black small square");
			allEmojiMap.put("U+25AB", "white small square");
			allEmojiMap.put("U+25FB", "white medium square");
			allEmojiMap.put("U+25FC", "black medium square");
			allEmojiMap.put("U+25FD", "white medium-small square");
			allEmojiMap.put("U+25FE", "black medium-small square");
			allEmojiMap.put("U+2B1B", "black large square");
			allEmojiMap.put("U+2B1C", "white large square");
			allEmojiMap.put("U+1F536", "large orange diamond");
			allEmojiMap.put("U+1F537", "large blue diamond");
			allEmojiMap.put("U+1F538", "small orange diamond");
			allEmojiMap.put("U+1F539", "small blue diamond");
			allEmojiMap.put("U+1F53A", "red triangle pointed up");
			allEmojiMap.put("U+1F53B", "red triangle pointed down");
			allEmojiMap.put("U+1F4A0", "diamond with a dot");
			allEmojiMap.put("U+1F518", "radio button");
			allEmojiMap.put("U+1F532", "black square button");
			allEmojiMap.put("U+1F533", "white square button");
			allEmojiMap.put("U+26AA", "white circle");
			allEmojiMap.put("U+26AB", "black circle");
			allEmojiMap.put("U+1F534", "red circle");
			allEmojiMap.put("U+1F535", "blue circle");
			allEmojiMap.put("U+1F3C1", "chequered flag");
			allEmojiMap.put("U+1F6A9", "triangular flag");
			allEmojiMap.put("U+1F38C", "crossed flags");
			allEmojiMap.put("U+1F3F4", "black flag");
			allEmojiMap.put("U+1F3F3", "white flag");
			allEmojiMap.put("U+1F3F3 U+FE0F U+200D U+1F308", "rainbow flag");
			allEmojiMap.put("U+1F1E6 U+1F1E8", "Ascension Island");
			allEmojiMap.put("U+1F1E6 U+1F1E9", "Andorra");
			allEmojiMap.put("U+1F1E6 U+1F1EA", "United Arab Emirates");
			allEmojiMap.put("U+1F1E6 U+1F1EB", "Afghanistan");
			allEmojiMap.put("U+1F1E6 U+1F1EE", "Anguilla");
			allEmojiMap.put("U+1F1E6 U+1F1F1", "Albania");
			allEmojiMap.put("U+1F1E6 U+1F1F2", "Armenia");
			allEmojiMap.put("U+1F1E6 U+1F1F4", "Angola");
			allEmojiMap.put("U+1F1E6 U+1F1F6", "Antarctica");
			allEmojiMap.put("U+1F1E6 U+1F1F7", "Argentina");
			allEmojiMap.put("U+1F1E6 U+1F1F8", "American Samoa");
			allEmojiMap.put("U+1F1E6 U+1F1F9", "Austria");
			allEmojiMap.put("U+1F1E6 U+1F1FA", "Australia");
			allEmojiMap.put("U+1F1E6 U+1F1FC", "Aruba");
			allEmojiMap.put("U+1F1E6 U+1F1FF", "Azerbaijan");
			allEmojiMap.put("U+1F1E7 U+1F1E7", "Barbados");
			allEmojiMap.put("U+1F1E7 U+1F1E9", "Bangladesh");
			allEmojiMap.put("U+1F1E7 U+1F1EA", "Belgium");
			allEmojiMap.put("U+1F1E7 U+1F1EB", "Burkina Faso");
			allEmojiMap.put("U+1F1E7 U+1F1EC", "Bulgaria");
			allEmojiMap.put("U+1F1E7 U+1F1ED", "Bahrain");
			allEmojiMap.put("U+1F1E7 U+1F1EE", "Burundi");
			allEmojiMap.put("U+1F1E7 U+1F1EF", "Benin");
			allEmojiMap.put("U+1F1E7 U+1F1F2", "Bermuda");
			allEmojiMap.put("U+1F1E7 U+1F1F3", "Brunei");
			allEmojiMap.put("U+1F1E7 U+1F1F4", "Bolivia");
			allEmojiMap.put("U+1F1E7 U+1F1F6", "Caribbean Netherlands");
			allEmojiMap.put("U+1F1E7 U+1F1F7", "Brazil");
			allEmojiMap.put("U+1F1E7 U+1F1F8", "Bahamas");
			allEmojiMap.put("U+1F1E7 U+1F1F9", "Bhutan");
			allEmojiMap.put("U+1F1E7 U+1F1FB", "Bouvet Island");
			allEmojiMap.put("U+1F1E7 U+1F1FC", "Botswana");
			allEmojiMap.put("U+1F1E7 U+1F1FE", "Belarus");
			allEmojiMap.put("U+1F1E7 U+1F1FF", "Belize");
			allEmojiMap.put("U+1F1E8 U+1F1E6", "Canada");
			allEmojiMap.put("U+1F1E8 U+1F1E9", "Congo - Kinshasa");
			allEmojiMap.put("U+1F1E8 U+1F1EB", "Central African Republic");
			allEmojiMap.put("U+1F1E8 U+1F1EC", "Congo - Brazzaville");
			allEmojiMap.put("U+1F1E8 U+1F1ED", "Switzerland");
			allEmojiMap.put("U+1F1E8 U+1F1F0", "Cook Islands");
			allEmojiMap.put("U+1F1E8 U+1F1F1", "Chile");
			allEmojiMap.put("U+1F1E8 U+1F1F2", "Cameroon");
			allEmojiMap.put("U+1F1E8 U+1F1F3", "China");
			allEmojiMap.put("U+1F1E8 U+1F1F4", "Colombia");
			allEmojiMap.put("U+1F1E8 U+1F1F5", "Clipperton Island");
			allEmojiMap.put("U+1F1E8 U+1F1F7", "Costa Rica");
			allEmojiMap.put("U+1F1E8 U+1F1FA", "Cuba");
			allEmojiMap.put("U+1F1E8 U+1F1FB", "Cape Verde");
			allEmojiMap.put("U+1F1E8 U+1F1FD", "Christmas Island");
			allEmojiMap.put("U+1F1E8 U+1F1FE", "Cyprus");
			allEmojiMap.put("U+1F1E8 U+1F1FF", "Czechia");
			allEmojiMap.put("U+1F1E9 U+1F1EA", "Germany");
			allEmojiMap.put("U+1F1E9 U+1F1EC", "Diego Garcia");
			allEmojiMap.put("U+1F1E9 U+1F1EF", "Djibouti");
			allEmojiMap.put("U+1F1E9 U+1F1F0", "Denmark");
			allEmojiMap.put("U+1F1E9 U+1F1F2", "Dominica");
			allEmojiMap.put("U+1F1E9 U+1F1F4", "Dominican Republic");
			allEmojiMap.put("U+1F1E9 U+1F1FF", "Algeria");
			allEmojiMap.put("U+1F1EA U+1F1E8", "Ecuador");
			allEmojiMap.put("U+1F1EA U+1F1EA", "Estonia");
			allEmojiMap.put("U+1F1EA U+1F1EC", "Egypt");
			allEmojiMap.put("U+1F1EA U+1F1ED", "Western Sahara");
			allEmojiMap.put("U+1F1EA U+1F1F7", "Eritrea");
			allEmojiMap.put("U+1F1EA U+1F1F8", "Spain");
			allEmojiMap.put("U+1F1EA U+1F1F9", "Ethiopia");
			allEmojiMap.put("U+1F1EA U+1F1FA", "European Union");
			allEmojiMap.put("U+1F1EB U+1F1EE", "Finland");
			allEmojiMap.put("U+1F1EB U+1F1EF", "Fiji");
			allEmojiMap.put("U+1F1EB U+1F1F0", "Falkland Islands");
			allEmojiMap.put("U+1F1EB U+1F1F2", "Micronesia");
			allEmojiMap.put("U+1F1EB U+1F1F4", "Faroe Islands");
			allEmojiMap.put("U+1F1EB U+1F1F7", "France");
			allEmojiMap.put("U+1F1EC U+1F1E6", "Gabon");
			allEmojiMap.put("U+1F1EC U+1F1E7", "United Kingdom");
			allEmojiMap.put("U+1F1EC U+1F1E9", "Grenada");
			allEmojiMap.put("U+1F1EC U+1F1EA", "Georgia");
			allEmojiMap.put("U+1F1EC U+1F1EB", "French Guiana");
			allEmojiMap.put("U+1F1EC U+1F1EC", "Guernsey");
			allEmojiMap.put("U+1F1EC U+1F1ED", "Ghana");
			allEmojiMap.put("U+1F1EC U+1F1EE", "Gibraltar");
			allEmojiMap.put("U+1F1EC U+1F1F1", "Greenland");
			allEmojiMap.put("U+1F1EC U+1F1F2", "Gambia");
			allEmojiMap.put("U+1F1EC U+1F1F3", "Guinea");
			allEmojiMap.put("U+1F1EC U+1F1F5", "Guadeloupe");
			allEmojiMap.put("U+1F1EC U+1F1F6", "Equatorial Guinea");
			allEmojiMap.put("U+1F1EC U+1F1F7", "Greece");
			allEmojiMap.put("U+1F1EC U+1F1F9", "Guatemala");
			allEmojiMap.put("U+1F1EC U+1F1FA", "Guam");
			allEmojiMap.put("U+1F1EC U+1F1FC", "Guinea-Bissau");
			allEmojiMap.put("U+1F1EC U+1F1FE", "Guyana");
			allEmojiMap.put("U+1F1ED U+1F1F0", "Hong Kong SAR China");
			allEmojiMap.put("U+1F1ED U+1F1F3", "Honduras");
			allEmojiMap.put("U+1F1ED U+1F1F7", "Croatia");
			allEmojiMap.put("U+1F1ED U+1F1F9", "Haiti");
			allEmojiMap.put("U+1F1ED U+1F1FA", "Hungary");
			allEmojiMap.put("U+1F1EE U+1F1E8", "Canary Islands");
			allEmojiMap.put("U+1F1EE U+1F1E9", "Indonesia");
			allEmojiMap.put("U+1F1EE U+1F1EA", "Ireland");
			allEmojiMap.put("U+1F1EE U+1F1F1", "Israel");
			allEmojiMap.put("U+1F1EE U+1F1F2", "Isle of Man");
			allEmojiMap.put("U+1F1EE U+1F1F3", "India");
			allEmojiMap.put("U+1F1EE U+1F1F4", "British Indian Ocean Territory");
			allEmojiMap.put("U+1F1EE U+1F1F6", "Iraq");
			allEmojiMap.put("U+1F1EE U+1F1F7", "Iran");
			allEmojiMap.put("U+1F1EE U+1F1F8", "Iceland");
			allEmojiMap.put("U+1F1EE U+1F1F9", "Italy");
			allEmojiMap.put("U+1F1EF U+1F1EA", "Jersey");
			allEmojiMap.put("U+1F1EF U+1F1F2", "Jamaica");
			allEmojiMap.put("U+1F1EF U+1F1F4", "Jordan");
			allEmojiMap.put("U+1F1EF U+1F1F5", "Japan");
			allEmojiMap.put("U+1F1F0 U+1F1EA", "Kenya");
			allEmojiMap.put("U+1F1F0 U+1F1EC", "Kyrgyzstan");
			allEmojiMap.put("U+1F1F0 U+1F1ED", "Cambodia");
			allEmojiMap.put("U+1F1F0 U+1F1EE", "Kiribati");
			allEmojiMap.put("U+1F1F0 U+1F1F2", "Comoros");
			allEmojiMap.put("U+1F1F0 U+1F1F5", "North Korea");
			allEmojiMap.put("U+1F1F0 U+1F1F7", "South Korea");
			allEmojiMap.put("U+1F1F0 U+1F1FC", "Kuwait");
			allEmojiMap.put("U+1F1F0 U+1F1FE", "Cayman Islands");
			allEmojiMap.put("U+1F1F0 U+1F1FF", "Kazakhstan");
			allEmojiMap.put("U+1F1F1 U+1F1E6", "Laos");
			allEmojiMap.put("U+1F1F1 U+1F1E7", "Lebanon");
			allEmojiMap.put("U+1F1F1 U+1F1EE", "Liechtenstein");
			allEmojiMap.put("U+1F1F1 U+1F1F0", "Sri Lanka");
			allEmojiMap.put("U+1F1F1 U+1F1F7", "Liberia");
			allEmojiMap.put("U+1F1F1 U+1F1F8", "Lesotho");
			allEmojiMap.put("U+1F1F1 U+1F1F9", "Lithuania");
			allEmojiMap.put("U+1F1F1 U+1F1FA", "Luxembourg");
			allEmojiMap.put("U+1F1F1 U+1F1FB", "Latvia");
			allEmojiMap.put("U+1F1F1 U+1F1FE", "Libya");
			allEmojiMap.put("U+1F1F2 U+1F1E6", "Morocco");
			allEmojiMap.put("U+1F1F2 U+1F1E8", "Monaco");
			allEmojiMap.put("U+1F1F2 U+1F1E9", "Moldova");
			allEmojiMap.put("U+1F1F2 U+1F1EA", "Montenegro");
			allEmojiMap.put("U+1F1F2 U+1F1EC", "Madagascar");
			allEmojiMap.put("U+1F1F2 U+1F1ED", "Marshall Islands");
			allEmojiMap.put("U+1F1F2 U+1F1F0", "Macedonia");
			allEmojiMap.put("U+1F1F2 U+1F1F1", "Mali");
			allEmojiMap.put("U+1F1F2 U+1F1F3", "Mongolia");
			allEmojiMap.put("U+1F1F2 U+1F1F4", "Macau SAR China");
			allEmojiMap.put("U+1F1F2 U+1F1F5", "Northern Mariana Islands");
			allEmojiMap.put("U+1F1F2 U+1F1F6", "Martinique");
			allEmojiMap.put("U+1F1F2 U+1F1F7", "Mauritania");
			allEmojiMap.put("U+1F1F2 U+1F1F8", "Montserrat");
			allEmojiMap.put("U+1F1F2 U+1F1F9", "Malta");
			allEmojiMap.put("U+1F1F2 U+1F1FA", "Mauritius");
			allEmojiMap.put("U+1F1F2 U+1F1FB", "Maldives");
			allEmojiMap.put("U+1F1F2 U+1F1FC", "Malawi");
			allEmojiMap.put("U+1F1F2 U+1F1FD", "Mexico");
			allEmojiMap.put("U+1F1F2 U+1F1FE", "Malaysia");
			allEmojiMap.put("U+1F1F2 U+1F1FF", "Mozambique");
			allEmojiMap.put("U+1F1F3 U+1F1E6", "Namibia");
			allEmojiMap.put("U+1F1F3 U+1F1E8", "New Caledonia");
			allEmojiMap.put("U+1F1F3 U+1F1EA", "Niger");
			allEmojiMap.put("U+1F1F3 U+1F1EB", "Norfolk Island");
			allEmojiMap.put("U+1F1F3 U+1F1EC", "Nigeria");
			allEmojiMap.put("U+1F1F3 U+1F1EE", "Nicaragua");
			allEmojiMap.put("U+1F1F3 U+1F1F1", "Netherlands");
			allEmojiMap.put("U+1F1F3 U+1F1F4", "Norway");
			allEmojiMap.put("U+1F1F3 U+1F1F5", "Nepal");
			allEmojiMap.put("U+1F1F3 U+1F1F7", "Nauru");
			allEmojiMap.put("U+1F1F3 U+1F1FA", "Niue");
			allEmojiMap.put("U+1F1F3 U+1F1FF", "New Zealand");
			allEmojiMap.put("U+1F1F4 U+1F1F2", "Oman");
			allEmojiMap.put("U+1F1F5 U+1F1E6", "Panama");
			allEmojiMap.put("U+1F1F5 U+1F1EA", "Peru");
			allEmojiMap.put("U+1F1F5 U+1F1EB", "French Polynesia");
			allEmojiMap.put("U+1F1F5 U+1F1EC", "Papua New Guinea");
			allEmojiMap.put("U+1F1F5 U+1F1ED", "Philippines");
			allEmojiMap.put("U+1F1F5 U+1F1F0", "Pakistan");
			allEmojiMap.put("U+1F1F5 U+1F1F1", "Poland");
			allEmojiMap.put("U+1F1F5 U+1F1F3", "Pitcairn Islands");
			allEmojiMap.put("U+1F1F5 U+1F1F7", "Puerto Rico");
			allEmojiMap.put("U+1F1F5 U+1F1F8", "Palestinian Territories");
			allEmojiMap.put("U+1F1F5 U+1F1F9", "Portugal");
			allEmojiMap.put("U+1F1F5 U+1F1FC", "Palau");
			allEmojiMap.put("U+1F1F5 U+1F1FE", "Paraguay");
			allEmojiMap.put("U+1F1F6 U+1F1E6", "Qatar");
			allEmojiMap.put("U+1F1F7 U+1F1F4", "Romania");
			allEmojiMap.put("U+1F1F7 U+1F1F8", "Serbia");
			allEmojiMap.put("U+1F1F7 U+1F1FA", "Russia");
			allEmojiMap.put("U+1F1F7 U+1F1FC", "Rwanda");
			allEmojiMap.put("U+1F1F8 U+1F1E6", "Saudi Arabia");
			allEmojiMap.put("U+1F1F8 U+1F1E7", "Solomon Islands");
			allEmojiMap.put("U+1F1F8 U+1F1E8", "Seychelles");
			allEmojiMap.put("U+1F1F8 U+1F1E9", "Sudan");
			allEmojiMap.put("U+1F1F8 U+1F1EA", "Sweden");
			allEmojiMap.put("U+1F1F8 U+1F1EC", "Singapore");
			allEmojiMap.put("U+1F1F8 U+1F1EE", "Slovenia");
			allEmojiMap.put("U+1F1F8 U+1F1F0", "Slovakia");
			allEmojiMap.put("U+1F1F8 U+1F1F1", "Sierra Leone");
			allEmojiMap.put("U+1F1F8 U+1F1F2", "San Marino");
			allEmojiMap.put("U+1F1F8 U+1F1F3", "Senegal");
			allEmojiMap.put("U+1F1F8 U+1F1F4", "Somalia");
			allEmojiMap.put("U+1F1F8 U+1F1F7", "Suriname");
			allEmojiMap.put("U+1F1F8 U+1F1F8", "South Sudan");
			allEmojiMap.put("U+1F1F8 U+1F1FB", "El Salvador");
			allEmojiMap.put("U+1F1F8 U+1F1FD", "Sint Maarten");
			allEmojiMap.put("U+1F1F8 U+1F1FE", "Syria");
			allEmojiMap.put("U+1F1F8 U+1F1FF", "Swaziland");
			allEmojiMap.put("U+1F1F9 U+1F1E6", "Tristan da Cunha");
			allEmojiMap.put("U+1F1F9 U+1F1E9", "Chad");
			allEmojiMap.put("U+1F1F9 U+1F1EB", "French Southern Territories");
			allEmojiMap.put("U+1F1F9 U+1F1EC", "Togo");
			allEmojiMap.put("U+1F1F9 U+1F1ED", "Thailand");
			allEmojiMap.put("U+1F1F9 U+1F1EF", "Tajikistan");
			allEmojiMap.put("U+1F1F9 U+1F1F0", "Tokelau");
			allEmojiMap.put("U+1F1F9 U+1F1F1", "Timor-Leste");
			allEmojiMap.put("U+1F1F9 U+1F1F2", "Turkmenistan");
			allEmojiMap.put("U+1F1F9 U+1F1F3", "Tunisia");
			allEmojiMap.put("U+1F1F9 U+1F1F4", "Tonga");
			allEmojiMap.put("U+1F1F9 U+1F1F7", "Turkey");
			allEmojiMap.put("U+1F1F9 U+1F1FB", "Tuvalu");
			allEmojiMap.put("U+1F1F9 U+1F1FC", "Taiwan");
			allEmojiMap.put("U+1F1F9 U+1F1FF", "Tanzania");
			allEmojiMap.put("U+1F1FA U+1F1E6", "Ukraine");
			allEmojiMap.put("U+1F1FA U+1F1EC", "Uganda");
			allEmojiMap.put("U+1F1FA U+1F1F3", "United Nations");
			allEmojiMap.put("U+1F1FA U+1F1F8", "United States");
			allEmojiMap.put("U+1F1FA U+1F1FE", "Uruguay");
			allEmojiMap.put("U+1F1FA U+1F1FF", "Uzbekistan");
			allEmojiMap.put("U+1F1FB U+1F1E6", "Vatican City");
			allEmojiMap.put("U+1F1FB U+1F1EA", "Venezuela");
			allEmojiMap.put("U+1F1FB U+1F1EC", "British Virgin Islands");
			allEmojiMap.put("U+1F1FB U+1F1F3", "Vietnam");
			allEmojiMap.put("U+1F1FB U+1F1FA", "Vanuatu");
			allEmojiMap.put("U+1F1FC U+1F1F8", "Samoa");
			allEmojiMap.put("U+1F1FD U+1F1F0", "Kosovo");
			allEmojiMap.put("U+1F1FE U+1F1EA", "Yemen");
			allEmojiMap.put("U+1F1FE U+1F1F9", "Mayotte");
			allEmojiMap.put("U+1F1FF U+1F1E6", "South Africa");
			allEmojiMap.put("U+1F1FF U+1F1F2", "Zambia");
			allEmojiMap.put("U+1F1FF U+1F1FC", "Zimbabwe");


			Set<String> rcEmojiSet = new HashSet<String>(Arrays
					.asList("U+1F613", "U+1F637", "U+1F649", "U+1F609", "U+1F451", "U+1F366", "U+263A", "U+1F4AA", "U+1F556", "U+1F601", "U+1F61C", "U+2614", "U+1F62E", "U+1F393", "U+1F381", "U+1F680", "U+1F64A", "U+1F3B5", "U+1F60A", "U+1F339", "U+1F602", "U+270A", "U+1F614", "U+1F630", "U+1F6BF", "U+23F0", "U+1F004", "U+1F436", "U+1F60B", "U+1F61D", "U+2615", "U+1F62F", "U+1F382", "U+1F4A9", "U+1F3C0", "U+1F47F", "U+1F4A1", "U+1F3A4", "U+1F437", "U+1F603", "U+1F615", "U+1F48A", "U+1F37B", "U+270B", "U+1F4DA", "U+1F332", "U+1F631", "U+1F356", "U+1F60C", "U+1F61E", "U+1F44A", "U+1F4E2", "U+1F33B", "U+1F4A2", "U+1F52B", "U+1F616", "U+1F628", "U+270C", "U+1F48B", "U+1F632", "U+1F60D", "U+1F61F", "U+1F384", "U+1F3C2", "U+1F4A3", "U+26C4", "U+1F605", "U+1F629", "U+1F36B", "U+1F621", "U+1F633", "U+23F3", "U+1F30F", "U+1F60E", "U+1F494", "U+1F44C", "U+1F62A", "U+1F4A4", "U+1F525", "U+26C5", "U+1F319", "U+26A1", "U+1F606", "U+1F618", "U+1F35A", "U+1F47B", "U+1F484", "U+1F622", "U+1F634", "U+1F64F", "U+2744", "U+1F60F", "U+1F48D", "U+1F3B2", "U+1F44D", "U+1F62B", "U+1F635", "U+1F607", "U+1F3E1", "U+1F46A", "U+1F4DE", "U+1F611", "U+1F623", "U+26BD", "U+1F6B2", "U+2600", "U+1F47C", "U+1F4B0", "U+270F", "U+1F44E", "U+1F61A", "U+1F62C", "U+1F624", "U+1F6AB", "U+261D", "U+1F349", "U+1F636", "U+1F648", "U+1F608", "U+2B50", "U+1F377", "U+1F434", "U+1F389", "U+1F600", "U+1F612", "U+1F62D", "U+2601", "U+1F47D", "U+1F46B", "U+1F44F"));

			//只保留融云的表情
			for (String key : new HashSet<String>(allEmojiMap.keySet())) {
				if(!rcEmojiSet.contains(key)){
					allEmojiMap.remove(key);
				}
			}

		}


}
